### ISSUE TITLE
Productivity listed twice

### ISSUE THREAD

**Issue by McPerson** [ellite/Wallos#10]
Hey, I noticed "Productivity" is listed twice in the category drop down.

https://github.com/ellite/Wallos/blob/eee998c93d3e02a7de510f01aa03aac433635a77/db/commands.sql#L97-L113

Thanks for the super cool app!

**Comment by ellite** [comment]
Thank you. I've missed that. I'll change it.

**Comment by ellite** [comment]
Removed on https://github.com/ellite/Wallos/commit/7e4ca238111a77107b57c6d3edad847640dc9dd4
