### ISSUE TITLE
[BUG] notification email content text is incorrect when include some Chinese characters

### ISSUE THREAD

**Issue by WangLei1993** [ellite/Wallos#100]
When I view the email in RainLoop, I found the below picture, and the content text is incorrect.

![image](https://github.com/ellite/Wallos/assets/7637623/2ea8dced-13ef-409b-bab7-347649f4b409)

But I view it in the source email "https://mail.qq.com/", it is correct.

![image](https://github.com/ellite/Wallos/assets/7637623/11d3b28c-148e-49a6-8a9e-88de5112a208)

And then, to download the email to eml file and view it in IDE, the bug is 'charset=iso-8859-1'.

![image](https://github.com/ellite/Wallos/assets/7637623/c17116b3-d424-4e3d-b956-a0575e09a7d2)

After some search, I may find this link to solve the bug. More detail please to see that.

[phpmailer-character-encoding-issues](https://stackoverflow.com/questions/2491475/phpmailer-character-encoding-issues)

May you could fix this bug as soon as possible.

Thank you.

**Comment by ellite** [comment]
Should be fixed here https://github.com/ellite/Wallos/commit/4e7a526e34d26c2ff3f567900e4ded18aa0ce847
