### ISSUE TITLE
exec format error, supports ARM?

### ISSUE THREAD

**Issue by Harry-Edwards** [ellite/Wallos#101]
Hiya,

Keep getting "exec/usr/local/bin/docker-php-entrypoint: exec format error" when googling the issue, it comes down to an image not supporting ARM processors, does this one support ARM?

Thanks,

Harry

**Comment by ellite** [comment]
The :latest tag only supports arm64.
You need to install the :main tag.

`docker run -d --name wallos -v /path/to/config/wallos/db:/var/www/html/db \
-v /path/to/config/wallos/logos:/var/www/html/images/uploads/logos \
-e TZ=Europe/Berlin -p 8282:80 --restart unless-stopped \
bellamy/wallos:main`

**Comment by Harry-Edwards** [comment]
Thank you!
