### ISSUE TITLE
[Feature Request]  Matching Credit Card Logos

### ISSUE THREAD

**Issue by Node815** [ellite/Wallos#102]
For the Credit Card methods, we have two different ones we use in our household.  Visa and Mastercard,  To help differentiate which card a service is using, it would be ideal to have the Visa, Discover, and Amex  logo:
https://www.merchantsignage.visa.com/brand_guidelines
https://www.discover.com/company/newsroom/media-downloads/

Amex Logo = American Express, I coulnd't find an official one from them, but it should be easy enough to find one in the wild on the web!    I know this doesn't encompass all the payment methods, but these are pretty much the most common in the U.S. and worldwide as well. 

Then upon selecting the payment method, the user can then select the card type used and it would reflect it accordingly.

**Comment by ellite** [comment]
I actually had some CC types in the beginning, but then started finding more and more, and didn't want to go deeper on the rabbit hole. So I decided to just have "Credit Card".
If I have some time I might add some of them. But no promises.

**Comment by ellite** [comment]
You can now add custom payment methods.
Regards.
