### ISSUE TITLE
[BUG] Unable to select logo

### ISSUE THREAD

**Issue by brilletjuh** [ellite/Wallos#103]
When I try to add a logo to a subscription via the websearch, I get this error:
![image](https://github.com/ellite/Wallos/assets/8963620/3d53c1b2-045f-4a9b-b137-8bc16824fd22)

Also, when uploading an image manually, it is not updated, although I do get the notification that it did succeed.
Even after hard-refreshing the page, it is not updated.

**Comment by ellite** [comment]
What kind of installation do you have?

Can you open the network tab and see what error it shows on the request?
I would assume imagick is not installed.

**Comment by brilletjuh** [comment]
I run it on Raspbian using php8.3 on apache. I tried installing imagick and restarting apache, but the problem persists.
The request to add.php gives an empty response, but with a 500 Internal Server Error

**Comment by ellite** [comment]
I have no idea. Can you find the logs with the error message?

Maybe here `/var/log/apache2/error.log`

**Comment by brilletjuh** [comment]
It seems I had GD not installed (imagecreatefromstring was not found), so I installed  that, but then I got this error:
```
PHP Fatal error:  Uncaught ImagickException: WriteBlob Failed `../../images/uploads/logos/<filename>.png' @ error/png.c/MagickPNGErrorHandler/1642 in /var/www/html/wallos/endpoints/subscription/add.php:53
Stack trace:
#0 /var/www/html/wallos/endpoints/subscription/add.php(53): Imagick->writeImage()
#1 /var/www/html/wallos/endpoints/subscription/add.php(25): saveLogo()
#2 /var/www/html/wallos/endpoints/subscription/add.php(153): getLogoFromUrl()
#3 {main}
  thrown in /var/www/html/wallos/endpoints/subscription/add.php on line 53, referer: <domain>
```

**Comment by brilletjuh** [comment]
Problem solved, turned out to be a file permission/ownership problem...

**Comment by ellite** [comment]
Glad you got it working.
