### ISSUE TITLE
[FEATURE REQUEST] Cancellation period field

### ISSUE THREAD

**Issue by dudel** [ellite/Wallos#104]
For some subscriptions there is a cancellation period one has to adhere when they want to cancel a subscription. E.g. the next billing cycle starts on the 01.06. (First of July) but there is a 3 months cancellation period, thus the cancellation must be sent before 01.03. 

It would be nice to have such a field tracking the cancellation period. The input would be the same as for the next billing cycle field (without the date because it is based on the billing cycle date).

Furthermore if a cancellation period is set it would be nice to be notified before the start of the cancellation period.

**Comment by ellite** [comment]
Hi, thank you for the request.
The list of TODOs is long, so this won't be implemented for a while. Sorry.

**Comment by dudel** [comment]
No worries at all, thank you for this app. If I knew my way around I would have helped. I just thought it would be a useful feature for keeping track of various subscriptions and their deadlines.

**Comment by ellite** [comment]
Hi. Not exactly what you requested, but I just added a cancelation notification date field to the subscriptions.

**Comment by dudel** [comment]
Perfect, thank you!
