### ISSUE TITLE
Streamline Currency

### ISSUE THREAD

**Issue by ridizy** [ellite/Wallos#11]
This is a great start - thank you!

I selected USD as my default currency.  However, when I create a new subscription, it defaults to EUR.  I would expect it to default to USD.

Perhaps it would also be helpful if the currency order could be manually sorted.

**Comment by ellite** [comment]
Hi. You are absolutely right. Default currency should be the pre selected currency when adding a new subscription. This will go to the top of my list.
Manually sorting will not be a priority at the moment.

**Comment by ellite** [comment]
Main currency is now pre-selected when adding a new subscription https://github.com/ellite/Wallos/commit/7e4ca238111a77107b57c6d3edad847640dc9dd4

**Comment by ridizy** [comment]
I'm using the [latest docker image](https://hub.docker.com/layers/bellamy/wallos/latest/images/sha256-90b6cb14c466b0aaacd0bea36cce7bc7cdb60907c960bf19552992cca322132c?context=explore) and it still doesn't seem to default to my main currency.  I've tried selecting a different one, confirming it is saved, and then setting it back and it still isn't working. I also tried a different browser.

**Comment by ridizy** [comment]
Hmm...pulled [the next build](https://hub.docker.com/layers/bellamy/wallos/latest/images/sha256-88680441785fc2d8e4bd2ea93e59aba098e666cefe482c7fa08b42cc58fe5d95?context=explore) just now and it's working.  Thank you!

**Comment by ellite** [comment]
Fixed with this change https://github.com/ellite/Wallos/commit/90ac147e2cd846c7db49402a1a17f6dc6e583bf4
