### ISSUE TITLE
Web search function does not work

### ISSUE THREAD

**Issue by atongrun** [ellite/Wallos#115]
As shown in the image, the content is blank after searching
![image](https://github.com/ellite/Wallos/assets/76803960/286aa8f2-dd23-4fe1-881e-391886aa5d5f)

**Comment by ellite** [comment]
Maybe google images is not accessible?
I will try to implement an alternative search engine.

**Comment by atongrun** [comment]
> Maybe google images is not accessible? I will try to implement an alternative search engine.

It seems like my deployed machine needs a proxy to access Google Images😢😢😢
