### ISSUE TITLE
support another method of fixer api

### ISSUE THREAD

**Issue by voidtao** [ellite/Wallos#119]
Registering with fixer.io now requires verification of credit card information. However, apilayer, the company to which it belongs, does not need it. APIlayer also provides free fixer API quota. The difference between the two is that the URL and authentication method are different, and the results returned are the same. Therefore, I hope another fixer api call can be supported, thanks.

The document link as follows
https://apilayer.com/marketplace/fixer-api

The calling method as follows
`
curl --request GET 'https://api.apilayer.com/fixer/latest?base=USD&symbols=EUR,GBP' \
--header 'apikey: YOUR API KEY'
`

**Comment by ellite** [comment]
I'm low on time at the moment. But I'll add it to my list to have a look.

**Comment by ellite** [comment]
Should be available now https://github.com/ellite/Wallos/commit/0f19dd688fe3a2156e7d26d1bf1e1f8b30ce79ad

**Comment by voidtao** [comment]
> Should be available now [0f19dd6](https://github.com/ellite/Wallos/commit/0f19dd688fe3a2156e7d26d1bf1e1f8b30ce79ad)

Super efficient, thanks for the development.

**Comment by voidtao** [comment]
thanks.
