### ISSUE TITLE
Renaming a category does not appear to work

### ISSUE THREAD

**Issue by ridizy** [ellite/Wallos#12]
I attempted to rename a Category and it does not appear to save this change.  I've tabbed out of the field and clicked to save changes in other sections.  The renamed category is reverted when adding a new subscription or going back into settings.

**Comment by ellite** [comment]
Hi. You should click this icon in front of the field you want to save 
<img width="33" alt="Screenshot 2023-11-10 214447" src="https://github.com/ellite/Wallos/assets/3831180/fe6807f9-0e7d-4d5b-9310-f82e74677ec2">

**Comment by ridizy** [comment]
Thank you - sorry I missed that!
