### ISSUE TITLE
[BUG] Stats page erroneously show foreing currency amounts as local

### ISSUE THREAD

**Issue by jpbaril** [ellite/Wallos#120]
I currently have two subscriptions entered into Wallos, one in Canadian Dollars and one in US Dollars.
The Canadian one = 45,98 $CA
The US one = 3 $US

The stats page erroneously shows and calculates the 3 $US amount as if it was 3 $ CA.
![Capture d’écran du 2024-02-17 19-21-54](https://github.com/ellite/Wallos/assets/5779633/6721fd5b-c946-4357-b34c-7d64854b3e37)

**Comment by dy8013255** [comment]
我跟你遇到了一样的问题😂

**Comment by ellite** [comment]
Do you have this option selected `Always convert and show prices on my main currency (slower)` ? 
Then you might not have set a fixer api key or the exchange rates failed to update.

Do you have a date below currencies, like this?
`Exchange rates last updated on 2024-02-18`

**Comment by jpbaril** [comment]
It seems it resolved by itself after a few hours.
I had not selected "Always convert and show prices on my main currency (slower)".
I also had just got a Fixer API, and even though I saw in Fixer an API usage count, as you said maybe Wallos had not yet triggered a real exchange rates update.

**Comment by ellite** [comment]
Yes. That was the case.
Glad it is fixed.

How about you @dy8013255 ?
