### ISSUE TITLE
The statistical information is incorrect

### ISSUE THREAD

**Issue by hausen1012** [ellite/Wallos#132]
![image](https://github.com/ellite/Wallos/assets/50026605/b8dbdf50-a284-4ea6-92e2-effce7bfa496)
![image](https://github.com/ellite/Wallos/assets/50026605/cf231efa-074c-488c-8bd2-3954bb47491f)

**Comment by ellite** [comment]
You need a fixer api key to use statistics accurately when using multiple currencies.
That should be it.

**Comment by hausen1012** [comment]
Can I manually adjust it

**Comment by ellite** [comment]
Hi.👋 
On the setting page, there's a field for the fixer api key, together with instructions.
Did you add your key there?

**Comment by hausen1012** [comment]
Hello, I understand what you said, but I don't have a credit card and cannot register an account. I hope I can manually adjust the exchange rate because I only need to know an approximate amount and not be very accurate. I hope future versions can have this feature, thank you very much

**Comment by ellite** [comment]
Ah, got it.
There's no need to add manually. 
On the latest version of Wallos you can get your key from apilayer. There you don't need to add a credit card.
The link is in the settings page.
Regards.

**Comment by hausen1012** [comment]
It seems that this API is free, https://fx.cmbchina.com/api/v1/fx/rate . And my server is in China, so I can't find the logo, which is a bit inconvenient
