### ISSUE TITLE
Statistics are displayed incorrectly

### ISSUE THREAD

**Issue by Cyrker** [ellite/Wallos#136]
My monthly bill looks like this
<img width="381" alt="image" src="https://github.com/ellite/Wallos/assets/38664017/ee956ab3-1d3b-4091-bebe-b57f7fda6b74">

But the statistics show this
<img width="974" alt="image" src="https://github.com/ellite/Wallos/assets/38664017/1de34616-d8f3-44d7-a2be-ba9b68a13273">

Here are some of my settings

<img width="821" alt="image" src="https://github.com/ellite/Wallos/assets/38664017/eea8f180-1be4-4201-8aa4-31eec4c85d09">
<img width="1035" alt="image" src="https://github.com/ellite/Wallos/assets/38664017/b9244451-5311-4e4e-94ca-1f115f74eef9">

version Wallos v1.3.0

**Comment by ellite** [comment]
I believe you have selected Yearly instead of monthly when creating the subscriptions.

**Comment by Cyrker** [comment]
I did select monthly
<img width="790" alt="image" src="https://github.com/ellite/Wallos/assets/38664017/a00ea964-d66b-4b88-a6c5-abd40c75641b">
<img width="791" alt="image" src="https://github.com/ellite/Wallos/assets/38664017/03713911-d58c-49af-b7ff-71667339c3ac">

**Comment by ellite** [comment]
I will have to check after work.

**Comment by ellite** [comment]
Ah, I see the issue. 
The billing cycle should be 1 - Monthly and not 12 Monthly.
12 Monthly means you pay EVERY 12 MONTHS.

**Comment by Cyrker** [comment]
> Ah, I see the issue. The billing cycle should be 1 - Monthly and not 12 Monthly. 12 Monthly means you pay EVERY 12 MONTHS.
> 
> Regards.

oh! So that’s it, I thought the previous value was the payment on a certain day in a certain month
Thank you for your reply!
