### ISSUE TITLE
Are multiple logins supported?

### ISSUE THREAD

**Issue by nebbishOne** [ellite/Wallos#14]
Hello! I know the main install page suggests adding family members but from what I can see, anyone registered after the initial user just gets a name. I am not seeing any place to set a password for them, so they can sign in separately. 

Assuming I'm right about that, consider this my request to enable logins for more users. I'd like to be able to share this with my SO and have her see her name on the screen, when she logs in.   

Thanks for the great little app.

**Comment by ellite** [comment]
Hi.
For the moment only on account can login.
The idea with the household is that everyone can login with the same account and add the subscriptions for their household using the household member.
Implementing multi login will require a total redesign of the database, so, it will not be done for now, until I fix all the issues. Sorry.

**Comment by nebbishOne** [comment]
Understood, @ellite  - thanks for the reply.
