### ISSUE TITLE
[Feature Request] Add the ability to customize which expirations should be notified

### ISSUE THREAD

**Issue by spiezmaestro** [ellite/Wallos#140]
I have many monthly recurring subscriptions for which I would not want to get notifications every month. However, I'm very interested in being notified on the exceptions (which I pay for example only every 3 months, yearly, every 2 years, etc).

Maybe something like: do not notify when recurrence is under X days.

Thanks!

**Comment by ellite** [comment]
Hi.
Notifications are disabled by default and have to be enabled on the subscription form for the subscriptions you want to be notified.

Regards

**Comment by spiezmaestro** [comment]
Sorry, totally oversaw the notification per subscription. Brilliant, that is even better!
