### ISSUE TITLE
[Bug] settings page POST bad api_key with extra space

### ISSUE THREAD

**Issue by sliots** [ellite/Wallos#141]
In the POST request, "api_key" has an extra space, and the "provider" parameter cannot be saved because of the extra space.

https://github.com/ellite/Wallos/blob/c1231605a47475e69ee0c80d58c4e2a4c4ecb1bc/scripts/settings.js#L486

**Comment by ellite** [comment]
Should be fixed on https://github.com/ellite/Wallos/releases/tag/v1.4.1
