### ISSUE TITLE
USD to AUD currency conversion backwards

### ISSUE THREAD

**Issue by zach-sb** [ellite/Wallos#16]
I was unable to change my main currency in the settings ( #15 ), so instead I tried running `docker exec wallos php /var/www/html/endpoints/cronjobs/updateexchange.php` to update the exchange rate, since my currency should have been set when I signed up anyway. 

The exchange rates are updated and the changed values are shown on the subscription page, however they are  wrong (actually they are backwards). 

For example, My main currency is AUD, I have a subscription of $5USD. I would expect a converted result to be $7.86AUD. Instead, I get $3.18AUD (which would be $5AUD to $USD)

**Comment by ellite** [comment]
I will check it soon. Thank you for reporting.

**Comment by ellite** [comment]
Issue should be solved with https://github.com/ellite/Wallos/commit/7e4ca238111a77107b57c6d3edad847640dc9dd4
