### ISSUE TITLE
how to traslate the payments method

### ISSUE THREAD

**Issue by Raxiel1987** [ellite/Wallos#163]
i tried find the traslation for the payments method ( credit card, band debit and so on..) but i can't find where to traslate them
how to traslate them?

**Comment by ellite** [comment]
Hi! Good point. Those are not translated. I'll add it to my list.
Regards.

**Comment by ellite** [comment]
You can now rename / translate payment methods on https://github.com/ellite/Wallos/releases/tag/v1.12.0
