### ISSUE TITLE
Non-US calendar + 6 months payment

### ISSUE THREAD

**Issue by janaxhell** [ellite/Wallos#164]
Maybe it's me, but I cannot find a way to set a subscription as "twice a year" or "every 6 months". If I set it as Billing Cyle = 2 / Yearly, it saves as Every 2 Years.
Also, is it possible to set the calendar in a non-US format like dd-mm-yyyy?

**Comment by ellite** [comment]
Hi.
To set a subscription every 6 months you should select
6 - Monthly

I really have to find a better way to present this. Is generating too much confusion.


As for the calendar, it is a simple html input type date. It takes the localization settings from the browser or OS settings.
To me it shows as dd/mm/yyyy

Reagrds.

**Comment by janaxhell** [comment]
Ok, thanks for the 6- Monthly.
About calendar: since most of the internet is in English and specific app-related words are in english, I prefer to keep my environment in english to find info more easily. And I would like to set the calendar independently as non-US. No problem if it's not possible, it's just a tiny annoyance. 
Very handy tool by the way.

**Comment by ellite** [comment]
I believe Locale settings are separated from language. You can change those independently.
For example
On iOS: Settings -> Language & Region and change the date format.
On windows: Settings -> Time & Language -> Language & Region.

**Comment by janaxhell** [comment]
I use Wallos from Docker, do I have to set some ENV for that? As of now I have TZ=Europe/Rome. Is the Windows setting relevant for something running on a linux machine?

**Comment by ellite** [comment]
1. No, there's nothing you can add to the ENV that will change that.
2. Yes, the client where you're accessing the app is responsible for rendering that field.
You can read more about form localization here: https://www.w3.org/International/wiki/Locale-based_forms

**Comment by ellite** [comment]
Maybe the browser overrides some of those settings. Sorry, can't really help you there.
