### ISSUE TITLE
smtp settings don't allow "no login" 

### ISSUE THREAD

**Issue by K1WIZ** [ellite/Wallos#167]
I have a local mail relay on the LAN that does not require SMTP authentication for mail originating on local subnet.  Wallos does not allow saving an SMTP host without a user or password.   There should be an option for this.

**Comment by ellite** [comment]
Hi, I'll add that to my list.

**Comment by K1WIZ** [comment]
here's what I see on my postfix mail server:

eb 28 21:40:50 lanmail postfix/smtpd[53511]: connect from unknown[10.0.1.88]
Feb 28 21:40:50 lanmail postfix/smtpd[53511]: SSL_accept error from unknown[10.0.1.88]: -1
Feb 28 21:40:50 lanmail postfix/smtpd[53511]: warning: TLS library problem: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../ssl/record/rec_layer_s3.c:1543:SSL alert number 48:
Feb 28 21:40:50 lanmail postfix/smtpd[53511]: lost connection after STARTTLS from unknown[10.0.1.88]
Feb 28 21:40:50 lanmail postfix/smtpd[53511]: disconnect from unknown[10.0.1.88] ehlo=1 starttls=0/1 commands=1/2
Feb 28 21:40:50 lanmail postfix/smtpd[53511]: connect from unknown[10.0.1.88]
Feb 28 21:40:50 lanmail postfix/smtpd[53511]: SSL_accept error from unknown[10.0.1.88]: -1
Feb 28 21:40:50 lanmail postfix/smtpd[53511]: warning: TLS library problem: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../ssl/record/rec_layer_s3.c:1543:SSL alert number 48:
Feb 28 21:40:50 lanmail postfix/smtpd[53511]: lost connection after STARTTLS from unknown[10.0.1.88]
Feb 28 21:40:50 lanmail postfix/smtpd[53511]: disconnect from unknown[10.0.1.88] ehlo=1 starttls=0/1 commands=1/2

**Comment by K1WIZ** [comment]
10.0.1.88 is the IP address of the app running in docker.

**Comment by stepanov1975** [comment]
Woold like option of SMTP host without a user or password as well. Thanks for very nice app!

**Comment by m-primo** [comment]
Hello.
Any update on this?

**Comment by ellite** [comment]
Hi. No updates yet.

**Comment by llzzrrdd** [comment]
yes it is quite an overkill for self-hosted wallos & smtp relay to create users and manage SSL. thank you in advance for the fix!

**Comment by ellite** [comment]
Hi, sorry. Totally forgot about this.
I have no idea how that would work.
Would it be as easy as allow to save the smtp settings without credentials and skip the authentication step, then?

**Comment by llzzrrdd** [comment]
in my case I am also struggling with the strict SSL or TLS --> maybe indeed if there was an option with no encryption / no credentials, would be much better for such usage with "safe" smtp relays. thanks!
