### ISSUE TITLE
Reverse Proxy Errors - Site Service Worker Redirections

### ISSUE THREAD

**Issue by cyclistguy** [ellite/Wallos#168]
There appears to be an issue when using Wallos behind a reverse Proxy .  The error results in the login page not being displayed.  Clearing the cache or multiple refreshes sometimes fixes the issue.  

In Safari, the following error is displayed:  "Safari can't open the page.  The error was: "Response served by service worker has redirections."

The following error is displayed in page inspect in Brave:
![CleanShot 2024-02-29 at 13 05 02@2x](https://github.com/ellite/Wallos/assets/82789156/30cc5f8a-eb37-4dde-8270-2e07e2d7acd9)

**Comment by ellite** [comment]
Hi, could you fix it?

**Comment by cyclistguy** [comment]
> Hi, could you fix it?

Actually, no.  On further review it effects all browsers.  Appears to be an issue with the page itself that will need to be fixed by the dev.

**Comment by TheOfficialBurner** [comment]
same here, with traefik. docker logs report:
127.0.0.1 - 01/Mar/2024:17:20:49 +0100 "GET /index.php" 200
127.0.0.1 - 01/Mar/2024:17:20:53 +0100 "POST /login.php" 302
127.0.0.1 - 01/Mar/2024:17:20:53 +0100 "GET /index.php" 200
127.0.0.1 - 01/Mar/2024:17:21:05 +0100 "GET /logout.php" 302
127.0.0.1 - 01/Mar/2024:17:21:05 +0100 "GET /index.php" 302

**Comment by ellite** [comment]
Hi. Can you try to Hard Refresh (ctrl + shift + r) ?
Otherwise you can try to unregister the service workers by opening the developer tools on the browser. Going to the tab Application and at the top there's Service Workers, select it and click Unregister.

![Screenshot 2024-03-01 215646](https://github.com/ellite/Wallos/assets/3831180/b81fe455-eab4-4b34-b036-a39554f0d3a4)

Thanks.

**Comment by TheOfficialBurner** [comment]
Hi, 

Hard Refresh works, so does unregister the worker, but only once. 
The Error keeps coming back, everytime i login or logout. So i have to Hard Refresh the page again to continue my work. 

Thanks

**Comment by ellite** [comment]
Thank you for trying.
I will try to reproduce it on my side, to try to fix it.

**Comment by ellite** [comment]
I would appreciate if you could test this image when you have time:

bellamy/wallos:pwa_fix

You might have to manually unregister the worker, but it should work after that.
Thank you in advance.

**Comment by TheOfficialBurner** [comment]
Hi there, 

the above Image works great and it is much faster. - i had to unregister the worker.
Thank you very much!

**Comment by ellite** [comment]
Awesome, thank you very much for testing.
I'm merging a security issue and after that I'll create a release with this.

**Comment by ellite** [comment]
Thank you @TheOfficialBurner for testing. It is released on version 1.11.3

Hope your issue is also fixed @cyclistguy .

**Comment by cyclistguy** [comment]
Thanks for the quick turnaround @ellite !  Works for me now too.

**Comment by ellite** [comment]
Perfect. Thank you for confirming.

**Comment by TheOfficialBurner** [comment]
@ellite thank you for that quick fix!!! - works great
