### ISSUE TITLE
Email notifications not working.

### ISSUE THREAD

**Issue by f021930c** [ellite/Wallos#17]
I'm running into a little hiccup while testing email notifications, and it seems like the snag might be due to using the sender's email address as the username.

`Fatal error: Uncaught PHPMailer\PHPMailer\Exception: SMTP Error: data not accepted. in /var/www/html/libs/PHPMailer/PHPMailer.php:2055 Stack trace: #0 /var/www/html/libs/PHPMailer/PHPMailer.php(1682): PHPMailer\PHPMailer\PHPMailer->smtpSend('Date: Fri, 10 N...', 'This is a test ...') #1 /var/www/html/libs/PHPMailer/PHPMailer.php(1516): PHPMailer\PHPMailer\PHPMailer->postSend() #2 /var/www/html/endpoints/notifications/sendtestmail.php(56): PHPMailer\PHPMailer\PHPMailer->send() #3 {main} thrown in /var/www/html/libs/PHPMailer/PHPMailer.php on line 2055`

https://ibb.co/vcwprGR

Payload

`{"smtpaddress":"smtp.sendgrid.net","smtpport":"587","smtpusername":"apikey","smtppassword":"SecurePassword"}`

**Comment by ellite** [comment]
Thank you for reporting it. I will have a look soon.

**Comment by esmoyer** [comment]
Giving some additional info; SMTP2Go give this reject reason; not sure if it's also why sendgrid would have the issue:

![image](https://github.com/ellite/Wallos/assets/17444085/36ab5101-cf84-4644-bddc-d61be09ae9b3)

**Comment by bonny1992** [comment]
Same issue:

```
Fatal error: Uncaught PHPMailer\PHPMailer\Exception: SMTP Error: data not accepted. in /var/www/html/libs/PHPMailer/PHPMailer.php:2055 Stack trace: #0 /var/www/html/libs/PHPMailer/PHPMailer.php(1682): PHPMailer\PHPMailer\PHPMailer->smtpSend('Date: Sun, 12 N...', 'This is a test ...') #1 /var/www/html/libs/PHPMailer/PHPMailer.php(1516): PHPMailer\PHPMailer\PHPMailer->postSend() #2 /var/www/html/endpoints/notifications/sendtestmail.php(56): PHPMailer\PHPMailer\PHPMailer->send() #3 {main} thrown in /var/www/html/libs/PHPMailer/PHPMailer.php on line 2055
```
With zoho.eu `smtppro.zoho.eu` SMTP endpoint.

**Comment by ellite** [comment]
I think some services require the sender email to be something specific. I will make that field editable by the user. It's on the list.

**Comment by ellite** [comment]
Now you can set your own From address.
https://github.com/ellite/Wallos/commit/0b6246b09db6a9e1634d300cb0f89d0f9de241ea
Hopefully this fixes it.

**Comment by bonny1992** [comment]
> Now you can set your own From address. [0b6246b](https://github.com/ellite/Wallos/commit/0b6246b09db6a9e1634d300cb0f89d0f9de241ea) Hopefully this fixes it.

Mmh.
Still got it in the latest docker build.

My settings are:
SMTP Host: `smtppro.zoho.eu`
SMTP Port: `587`
SMTP Username: `my zoho.eu email alias`
SMTP Password: `my per-app password`
From Email: `Wallos <my zoho.eu email alias>`

I might be doing something wrong here, ofc.

**Comment by devzwf** [comment]
> I might be doing something wrong here, ofc.

Can you try to put only an email  in the from field ?
like  recipient@domain.com
nothing else 
let me know

**Comment by f021930c** [comment]
@ellite  No, that didn't fix the issue.

here is the below error

`Fatal error: Uncaught PHPMailer\PHPMailer\Exception: SMTP Error: data not accepted. in /var/www/html/libs/PHPMailer/PHPMailer.php:2055 Stack trace: #0 /var/www/html/libs/PHPMailer/PHPMailer.php(1682): PHPMailer\PHPMailer\PHPMailer->smtpSend('Date: Thu, 23 N...', 'This is a test ...') #1 /var/www/html/libs/PHPMailer/PHPMailer.php(1516): PHPMailer\PHPMailer\PHPMailer->postSend() #2 /var/www/html/endpoints/notifications/sendtestmail.php(57): PHPMailer\PHPMailer\PHPMailer->send() #3 {main} thrown in /var/www/html/libs/PHPMailer/PHPMailer.php on line 2055`

https://ibb.co/DKybDSf

**Comment by Presoon** [comment]
I have same issue. Even after providing "From" input value, there's still an error: 
`Fatal error: Uncaught PHPMailer\PHPMailer\Exception: SMTP Error: The following recipients failed: perpetual234@xxx.xx: <wallos@wallosapp.com>: Sender address rejected: not owned by user noreply@xxxx.xx in /var/www/html/libs/PHPMailer/PHPMailer.php:2086 Stack trace: #0 /var/www/html/libs/PHPMailer/PHPMailer.php(1682): PHPMailer\PHPMailer\PHPMailer->smtpSend('Date: Thu, 23 N...', 'This is a test ...') #1 /var/www/html/libs/PHPMailer/PHPMailer.php(1516): PHPMailer\PHPMailer\PHPMailer->postSend() #2 /var/www/html/endpoints/notifications/sendtestmail.php(57): PHPMailer\PHPMailer\PHPMailer->send() #3 {main} thrown in /var/www/html/libs/PHPMailer/PHPMailer.php on line 2086`

It looks that this field doesn't matter, cause it still trying to send as wallos@wallosapp.com.

**Comment by ZetaExx** [comment]
Just a thought - excuse myself if it is a dump one - maybe it has something to do with the protocol too?
I noticed in the sendtestmail.php and sendnotification.php the protocol is fixed to TLS.
For example, my provider is excepting StartTLS with port 587. And if i try port 465 wallos isn't responding for about a minute - didn't wok as wall btw.

**Comment by devzwf** [comment]
@ellite first  i think  the table notification contains 
`from_email` and not `fromEmail`
in sendnotifications.php 
so 
` $fromEmail = $row["fromEmail"] ?? "wallos@wallosapp.com";`
always return wallos@wallosapp.com

**Comment by devzwf** [comment]
And i am agree with @ZetaExx .... i have tried many type and only the one who do TLS works.

**Comment by devzwf** [comment]
Please try with tag main and let me know.
this will probably not fix the TLS issue but for all the other should be rolling

**Comment by Presoon** [comment]
Working fine now ;)

**Comment by esmoyer** [comment]
Working for me with SMTP2Go!

**Comment by bonny1992** [comment]
I too confirm it's working using the `main` docker tag.
Many thanks for the fix!

**Comment by ellite** [comment]
It's been release on dev, main and latest. Thank you very much for the fix. I didn't have any time this week.

**Comment by f021930c** [comment]
Thanks for the fix.

**Comment by ellite** [comment]
It's now also available on latest.
