### ISSUE TITLE
Provide alternate image registry to dockerhub

### ISSUE THREAD

**Issue by onedr0p** [ellite/Wallos#177]
Hi 👋🏼 Awesome project here...

Dockerhub has aggressive pull rate and retention limits on container images, it would be awesome if you could push the image to Github Container Registry (GHCR) too. GHCR is free for open source projects and integrates into your GitHub repository here.

Thanks!

**Comment by ellite** [comment]
It's an excellent idea, but I am not familiar with GHCR and it was a contributor who built the github action I use to create and push the images.
If someone implements it, I will gladly merge it.
Otherwise maybe at some point I have the time to try to learn how to implement this.

Regrds.
