### ISSUE TITLE
Implement roadrunner

### ISSUE THREAD

**Issue by onedr0p** [ellite/Wallos#178]
Hi again 👋

I'm not sure how interested you are in improving the architecture of your app but [Roadrunner](https://github.com/roadrunner-server/roadrunner) is a really cool project that implements a webserver into your PHP application.

This would make nginx or Apache obsolete, especially in the docker container and also allow for running the container rootless and as a single process.

Anyways thanks for reading, keep up the good work 👍

**Comment by ellite** [comment]
Hi, thank you for the recommendation. I will check it out, but with the availability I have at the moment, it will not happen any time soon.

Regards.
