### ISSUE TITLE
[BUG] On initial registration page, logo can be cut off

### ISSUE THREAD

**Issue by boc-the-git** [ellite/Wallos#179]
Whilst I assume this is something likely dependent on resolution, this shows what the initial registration page looks like on my screen. Note the scroll bar on the right hand side, I can't scroll up any further.

![image](https://github.com/ellite/Wallos/assets/3479092/06824017-8fc2-46d6-b05d-72f7d62b98ab)

There is still downward scrolling to get me all the way to the register button, so functionally this isn't an issue, only visually.

If I zoom out in my browser, I am able to see the complete picture:
![image](https://github.com/ellite/Wallos/assets/3479092/58507180-04cf-473f-b056-f622b1752a5b)

My (Windows) system settings for reference: 
![image](https://github.com/ellite/Wallos/assets/3479092/bf9ef19c-1c65-43f5-8ce4-e868caacc084)

**Comment by boc-the-git** [comment]
This is obviously low priority, just raising for visibility!

**Comment by ellite** [comment]
Thank you for the report. I will have a look.
