### ISSUE TITLE
More 1 year

### ISSUE THREAD

**Issue by JamesDAdams** [ellite/Wallos#18]
Hi, 

i have multiple services when i pay for mutiple years directly, like my vpn (i pay for 3 years each time), an option for that would be verry cool :)

Thanks.

**Comment by ellite** [comment]
Hi, you can select 

Billing Cycle: 3 - Yearly
That makes it every 3 years.

I have to find better wording for that.

**Comment by JamesDAdams** [comment]
> Hi, you can select
> 
> Billing Cycle: 3 - Yearly That makes it every 3 years.
> 
> I have to find better wording for that.

Oh yes sorry, i'm tired :D
