### ISSUE TITLE
Subscription should be considered paid on the day it's set for

### ISSUE THREAD

**Issue by RichyHBM** [ellite/Wallos#180]
Currently it seems a subscription is only renewed the day after it's set to, this may be a locale difference but all of my subscription payments are taken at like 1am on the day it's set, where as on Wallos it doesn't get updated until the next day. I can fix this locally adding a 1 day interval in the update subscriptions script, but it seems like this could be at the very least a setting?

**Comment by ellite** [comment]
Hi, this was a conscious decision. To know what payments were due today.

**Comment by RichyHBM** [comment]
Fair enough.

For anyone that want's the functionality described, I made my own docker file that patches
```
FROM bellamy/wallos:latest

RUN sed -i "s/$currentDate = new DateTime();/\$currentDate = new DateTime();\$currentDate->add(DateInterval::createFromDateString('1 day'));/g" /var/www/html/endpoints/cronjobs/updatenextpayment.php
```
