### ISSUE TITLE
[Feature Request] Manually Sorting Categories in Settings

### ISSUE THREAD

**Issue by cyclistguy** [ellite/Wallos#185]
As a User I'd like to be able to manually sort (i.e. drag and drop) the "Categories" list in Settings so that I don't need to delete and re-enter multiple categories to sort.

**Comment by ellite** [comment]
Hi, this was implemented on [1.12.0](https://github.com/ellite/Wallos/releases/tag/v1.12.0)

**Comment by cyclistguy** [comment]
Ah yes....but I don't see this implemented?  Am I missing something?  The list of categories seems static....

![CleanShot 2024-03-05 at 12 25 49@2x](https://github.com/ellite/Wallos/assets/82789156/dafe08fd-c956-4601-b27e-425711c16cb6)

**Comment by ellite** [comment]
You have to update your docker image to 12.0.0.
You can check on the about section which version you are running.

**Comment by cyclistguy** [comment]
That explains it!  Didn't realize this was just released.  All good!
