### ISSUE TITLE
[Feature Request] Filtering in Subscription View

### ISSUE THREAD

**Issue by cyclistguy** [ellite/Wallos#186]
As a User I'd like to be be able to "filter" by Category in the Subscription View.  E.g. If I select the category "Software", only those subscriptions with the Software label will displayed and all others will be hidden.

**Comment by rajivvishwa** [comment]
+1 one to this feature.

**Comment by ellite** [comment]
Available on https://github.com/ellite/Wallos/releases/tag/v1.15.0

**Comment by cyclistguy** [comment]
Awesome @ellite !  Works great.
