### ISSUE TITLE
Two emails per reminder are sent 

### ISSUE THREAD

**Issue by Node815** [ellite/Wallos#187]
For some reason, I get two emails from "Wallos Notification"  for each subscription up for renewal.   The Docker Logs, I'm afraid are very sparse and don't indicate why.  My emails were sent at 09:00:00 during this cycle:

![image](https://github.com/ellite/Wallos/assets/20736534/8fe63e0f-0c23-4645-9362-2eaa0bba295a)

I can log into the container, but if you tell me where the email logs are stored, I can grab those for you.

**Comment by ellite** [comment]
Hi.Thank you for the report. 
Are you getting both emails for the same subscriptions?

**Comment by Node815** [comment]
Yes for the same subscription.  To the same inbox.

**Comment by ellite** [comment]
Thanks. I'll try to figure out what's happening.

**Comment by NightHawkATL** [comment]
I am seeing this also.
![image](https://github.com/ellite/Wallos/assets/8395658/d245bae7-ed87-44b4-b7f3-72f4680ad28b)

**Comment by Node815** [comment]
For what it's worth, there were no duplicates in the database when I explored it using a database explorer so that could probably be ruled out as a suspect.

**Comment by ellite** [comment]
If you have household members without an email address set, the email will be sent to the email defined on the account.

But I'm assuming that this is not the case.

Couldn't find the issue yet.

**Comment by NightHawkATL** [comment]
just one user here.

**Comment by Node815** [comment]
> If you have household members without an email address set, the email will be sent to the email defined on the account.
> 
> But I'm assuming that this is not the case.
> 
> Couldn't find the issue yet.

I have two other household members, but their e-mail is not provided in the app.   I have mine as the primary go to email for the notifications and planned on using a universal inbox for those down the road soon.

**Comment by ellite** [comment]
Just an update. I haven't found the issue yet.

**Comment by NightHawkATL** [comment]
I did add a second person and then remove them. Maybe the removal didn't remove them from the notifications?

**Comment by ridizy** [comment]
I am receiving duplicate e-mails as well.  I have two other members of my household and neither has an e-mail address set.  The duplicate e-mails are being sent to me for a subscription that is "Paid by" me.

**Comment by ellite** [comment]
I believe the issue is that the cronjobs are running twice.
Once as the user and once as the system:

```
/var/www/html # crontab -l
# Run the scripts every day
0 1 * * * /usr/local/bin/php /var/www/html/endpoints/cronjobs/updatenextpayment.php >> /var/log/cron/updatenextpayment.log 2>&1
0 2 * * * /usr/local/bin/php /var/www/html/endpoints/cronjobs/updateexchange.php >> /var/log/cron/updateexchange.log 2>&1
0 9 * * * /usr/local/bin/php /var/www/html/endpoints/cronjobs/sendnotifications.php >> /var/log/cron/sendnotifications.log 2>&1
/var/www/html # cat /etc/cron.d/cronjobs
# Run the scripts every day
0 1 * * * /usr/local/bin/php /var/www/html/endpoints/cronjobs/updatenextpayment.php >> /var/log/cron/updatenextpayment.log 2>&1
0 2 * * * /usr/local/bin/php /var/www/html/endpoints/cronjobs/updateexchange.php >> /var/log/cron/updateexchange.log 2>&1
0 9 * * * /usr/local/bin/php /var/www/html/endpoints/cronjobs/sendnotifications.php >> /var/log/cron/sendnotifications.log 2>&1
```

I'll try to fix this.

**Comment by ellite** [comment]
Just released 1.17.1 that disabled the cronjobs for the user, so they don't run twice.
Hopefully this fixes it 🤞

**Comment by ridizy** [comment]
I just had a reminder fire today, and I only received it once.  Thank you!

**Comment by ellite** [comment]
Perfect.
Thanks for confirming.
