### ISSUE TITLE
Option paid by multiple people

### ISSUE THREAD

**Issue by JamesDAdams** [ellite/Wallos#19]
Hi,

for multiple services (VPN, Spotify) we are multiple personnes for pay the subscription, that would be verry great to have an option for select multiple personnes in "Paid by"

Thanks.
<img width="116" alt="image" src="https://github.com/ellite/Wallos/assets/20860324/d91dab33-a1b0-4de5-9998-38d5ac63426c">

**Comment by ellite** [comment]
Hi, thank you for the suggestion.
I checked what I would need to change, and I don't have time to implement it for now.

**Comment by ridizy** [comment]
Just adding a couple of ideas for alternative solutions:

1. Creating a new "Household Member" with multiple names.  This may not be ideal depending on how the data gets used, but it wouldn't require any code changes
2. Use tags for "Paid by" where multiple could be added.  This would provide more flexibility but requires some significant code changes

I like the idea of multiple persons as I think about how, in the future, the data could potentially be used for reporting and analysis.

**Comment by ellite** [comment]
Hi. Not on the priorities to be implemented at the moment.
Closing the issue for now.
Thank you for the request.
