### ISSUE TITLE
There should be a 'discussion' group added to this repo

### ISSUE THREAD

**Issue by johnsturgeon** [ellite/Wallos#196]
I was able to search closed issues for my answer (just what is 'billing cycle') but it would be nice to have a discussion forum opened up on this repo.

**Comment by ellite** [comment]
Sure. Added one https://github.com/ellite/Wallos/discussions/200

**Comment by johnsturgeon** [comment]
Holy cow that was fast!

**Comment by ellite** [comment]
👌
