### ISSUE TITLE
[Feature Request] Personalize Avatar

### ISSUE THREAD

**Issue by cyclistguy** [ellite/Wallos#209]
As a User, I'd like to be able to upload a picture under Personal Details (vs using a "smiley face") so I may personalize my app experience.
![CleanShot 2024-03-09 at 16 53 47@2x](https://github.com/ellite/Wallos/assets/82789156/2c688b94-490b-4f72-86fa-9507048667f4)

**Comment by ellite** [comment]
Hi. This one is not on the list for now.
I might have a look into it when I have more time.

Thank you for the request.
Regards.

**Comment by ellite** [comment]
It's available on 1.18.0
Thanks @DanteB918

**Comment by cyclistguy** [comment]
Great....thank you!
