### ISSUE TITLE
[Feature Request] Manual Sorting of Payment Methods in Settings

### ISSUE THREAD

**Issue by cyclistguy** [ellite/Wallos#213]
As a User I want to be able to manually sort Payment Methods in Settings (similar to sorting for Categories) so when I filter by "Payment Method" when viewing my subscriptions, Payment Methods are listed in my preferred order.

**Comment by ellite** [comment]
Hi. This is on the list.
Regards.

**Comment by ellite** [comment]
It's available on 1.16.0
