### ISSUE TITLE
[Feature Request] See costs per Year in Table

### ISSUE THREAD

**Issue by dabenzel** [ellite/Wallos#216]
I'd like to see the costs per year in the Table as I have some subscriptions for every 3/6 months. With that, I can have a better overview

Like this:
![image](https://github.com/ellite/Wallos/assets/2480235/b79d9f96-96ab-4f17-b90b-505239d31efd)

**Comment by ellite** [comment]
You can convert all prices to monthly prices so you can directly compare them by enabling `Calculate and show monthly price for all subscriptions` on the settings page -> display settings
