### ISSUE TITLE
[Feature Request] Allow MySQL/Postgres as database

### ISSUE THREAD

**Issue by ToshY** [ellite/Wallos#219]
Would be nice to have the option to use databases like MySQL or Postgres.

**Comment by ellite** [comment]
Hi, I totally agree. But it is not a priority for me for now.
Sorry.

**Comment by ToshY** [comment]
Understandable. Thanks for taking the effort to reply 👍

**Comment by ellite** [comment]
No problem. Yeah, too many things to do outside of Wallos at the moment. 
Had to start prioritizing.
Will revisit all requests eventually.
Regards.
