### ISSUE TITLE
Can't select currency when creating an account

### ISSUE THREAD

**Issue by TheMadRey** [ellite/Wallos#22]
I have setup Wallos with docker compose. When i open the website and want to create an account i can't select a currency from the Combobox, it is just empty.

Firefox is my main browser, but i have also tried it with a clean Chrome install and there i have the same problem.

**Comment by ellite** [comment]
Can you please try to delete the wallos.db and restart the container?

**Comment by TheMadRey** [comment]
TThat didn't work, but i just tried

`docker-compose stop wallos`
`docker-compose rm wallos`
delete the wallos dir
`docker-compose up wallos`

Now works!
