### ISSUE TITLE
[Feature Request] Sort by next payment date within a group

### ISSUE THREAD

**Issue by rajivvishwa** [ellite/Wallos#222]
While the 'sort' feature allows users to group subscriptions by different categories, this action inadvertently resets any sorting previously applied by next payment date. 

To make the experience more intuitive, I propose the implementation of a feature that enables grouping followed by sorting within those groups.

For example, in the screenshot below, Amazon Prime should show up last in the last. 
![image](https://github.com/ellite/Wallos/assets/125708/c057632f-204b-4ed4-8a6a-ff25295752da)

**Comment by ellite** [comment]
Hi. I forgot to update this issue. This is now the default behaviour.
Regards
