### ISSUE TITLE
Email Sending BUG

### ISSUE THREAD

**Issue by xxlgenius** [ellite/Wallos#225]
I can't understand why this bug happened. But the bug can be reproduced.

I tested three types of email (Gmail, qq, Self-built mailbox).

Firstly, I try to use self-built mailbox, it only can be access in port 465. it awlays get error.
```
<br/>
<b>Fatal error</b>
:  Uncaught PHPMailer\PHPMailer\Exception: SMTP Error: Could not connect to SMTP host. in /var/www/html/libs/PHPMailer/PHPMailer.php:2244
Stack trace:
#0 /var/www/html/libs/PHPMailer/PHPMailer.php(2023): PHPMailer\PHPMailer\PHPMailer-&gt;smtpConnect(Array)
#1 /var/www/html/libs/PHPMailer/PHPMailer.php(1682): PHPMailer\PHPMailer\PHPMailer-&gt;smtpSend('Date: Wed, 13 M...', '\xE8\xBF\x99\xE6\x98\xAF\xE4\xB8\x80\xE6\x9D\xA1\xE6\xB5\x8B...')
#2 /var/www/html/libs/PHPMailer/PHPMailer.php(1516): PHPMailer\PHPMailer\PHPMailer-&gt;postSend()
#3 /var/www/html/endpoints/notifications/sendtestmail.php(58): PHPMailer\PHPMailer\PHPMailer-&gt;send()
#4 {main}
  thrown in <b>/var/www/html/libs/PHPMailer/PHPMailer.php</b>
on line <b>2244</b>
<br/>
```
Then I try the Gmail, it can be work on port 587 but still gets the same error on port 465.

The next mail (qq), it clear say can be work on both port 587 and 465. On port 587, it can be work, if the Mail from address keep the same as authorization user. But it still get the same error on port 465 : `Could not connect to SMTP host`. 

Please fix the bug.

**Comment by ellite** [comment]
Hi. Prior to 1.17.0 only TLS was supported. 1.17.0 allows you to select between TLS or SSL, so you should now be able to use port 465.
Regards.

**Comment by hausen1012** [comment]
I am currently using email to send and have found significant issues. When the configuration is incorrect, clicking on send email may cause the backend to freeze and access to timeout

**Comment by nicholas2471** [comment]
confirmed, same issue
