### ISSUE TITLE
New payment method logo error

### ISSUE THREAD

**Issue by rtomagnini** [ellite/Wallos#226]
When I try to add a new payment method and select a logo through the search or by adding it manually, the image doesn't appear. It shows as a broken link.

**Comment by rtomagnini** [comment]
![IMG_3083](https://github.com/ellite/Wallos/assets/84390264/702e5763-825c-4e7c-ad9f-9ecd2a166fd9)

**Comment by ellite** [comment]
Hi, can you right click on the image and click on inspect element and paste here the url that is failing?

Thanks.

**Comment by rtomagnini** [comment]
Hi, here is:

https://wallos.rtomagnini.synology.me/images/uploads/icons/1710313824-payments-Nubank.png

I can see the png on my server, but the link is broken
![image](https://github.com/ellite/Wallos/assets/84390264/6b886164-6cd4-4708-85ee-71578b99dbc5)

![image](https://github.com/ellite/Wallos/assets/84390264/47c3dcd4-2995-47f7-bc0a-062b8e893bfa)

**Comment by ellite** [comment]
I see the issue.
if you replace /icons by /logos the image is there.
I'm using the id of the payment method to change the folder where to pick the image for.
The payment methods already on the system have the logos on /icons and the custom payment methods on /logos
Seems that the ID is not incrementing but reusing IDs of deleted payment methods.
I will have to find a solution for it. I'll add it to my list.

Thank you for the report.
