### ISSUE TITLE
Warnung on Stats page when using weekly Billing Cycle

### ISSUE THREAD

**Issue by amueller80** [ellite/Wallos#23]
When I add a subscription with a weekly Billing Cycle and access the Stats page, I get the following warnings:
Warning: Undefined property: DateInterval::$weeks in /var/www/html/stats.php on line 101
Warning: Undefined property: DateInterval::$weeks in /var/www/html/stats.php on line 102

Without a weekly Billing Cycle, the warnings are not shown.
Otherwise, everything seems to work.

**Comment by ellite** [comment]
Thank you for the report. I will have a look soon.

**Comment by ellite** [comment]
Should be fixed with https://github.com/ellite/Wallos/commit/4e75456b16a703fbaf9fff653a912d75d38c82ef

**Comment by amueller80** [comment]
I can confirm, fixed now!
Thank you for the fast fix!
