### ISSUE TITLE
Managing Shared Expenses: Is It Feasible to Track Individual Payments and Totals

### ISSUE THREAD

**Issue by akadawa** [ellite/Wallos#232]
is it possible to have several users, assign the payments to the users and at the end see who has which expenses and what the total sum is? or is that too far away from the actual concept of the application?

**Comment by ellite** [comment]
Not sure I understood, but you can create household members and assign them to subscriptions. Then you sort or filter by household member on the subscriptions page and filter for household members on the stats page.
Maybe that's what you want, or I misunderstood your request.

Regards.
