### ISSUE TITLE
Stats calculations incorrect

### ISSUE THREAD

**Issue by sjafferali** [ellite/Wallos#25]
I have my main currency set to US Dollars, and removed all other currencies from the settings page. After doing this, I created a new yearly subscription for $695. After doing this, I click to the stats section and it appears the stats are way off. Screenshots attached. 

<img width="856" alt="Screenshot 2023-11-11 at 2 33 07 PM" src="https://github.com/ellite/Wallos/assets/11637345/79dd51bf-47c0-45b7-8e11-ebec514337e2">
<img width="882" alt="Screenshot 2023-11-11 at 2 33 16 PM" src="https://github.com/ellite/Wallos/assets/11637345/bbdd2d69-3c86-46b7-89c3-9fe8c92c6a09">

**Comment by ellite** [comment]
Thanks for the report. It should be fixed https://github.com/ellite/Wallos/commit/fca47d4d32d60b7bc6e16a7511a92660a975fa2c

**Comment by sjafferali** [comment]
@ellite Just tested. Looks great now! Thanks!

**Comment by bonny1992** [comment]
I'm having the same issue but the reverse.
Here's the image I'm using:
![image](https://github.com/ellite/Wallos/assets/1154368/d1e52ab4-e208-4600-8330-e5fa2b0bf7f9)

With these subscription set:
![image](https://github.com/ellite/Wallos/assets/1154368/6dc42e09-2c75-4a88-a70d-4935211265a4)
(I have a bit more but not enough)
And here's the stats:
![image](https://github.com/ellite/Wallos/assets/1154368/df065983-1ebc-470b-be5f-acf29ae683a0)

**Comment by ellite** [comment]
New attempt: https://github.com/ellite/Wallos/commit/74d851ea7a7647af1ea0f37612f6df959724be00

**Comment by bonny1992** [comment]
> New attempt: [74d851e](https://github.com/ellite/Wallos/commit/74d851ea7a7647af1ea0f37612f6df959724be00)

It seems that now the calculation is correct!
Very nice, thank you @ellite ! Wallos seems to be a really nice addon to my collection!
