### ISSUE TITLE
[Feature Request] make Payment icon search bigger

### ISSUE THREAD

**Issue by kazzyUK** [ellite/Wallos#252]
Hi.. Loving this tool so far.

Just wondering if in Settings, when adding a new Payment method.. the Search box to show the icons are so small, it hard to tell what it finds.. and after you select the icon, it still quite small.

Even on the Main page list view the icon is very small..  is there chance could add a bit more pixels to the size :)

Thanks, and keep up the fab work.

**Comment by ellite** [comment]
Hi. Could you please add a screenshot of how you see the search box? 

![image](https://github.com/ellite/Wallos/assets/3831180/b094498b-29b2-442e-9542-0ecaab7a6dfe)

I believe it is big enough, but maybe it's showing up differently for you.

Regards.

**Comment by kazzyUK** [comment]
Hi .. that looks nice,.,. 

for me via a browser i see the following.. hopefully the image comes up.

chrome:
![image](https://github.com/ellite/Wallos/assets/68235752/cb1da904-4dc0-40b2-8e72-0f425786acfa)

and in Edge
![image](https://github.com/ellite/Wallos/assets/68235752/5c845005-f41c-4af7-b443-9feac907aff8)

both browsers set to 100% zoom..   same on my Work laptop as it is on the home desktop.

Many thanks.

**Comment by ellite** [comment]
I'll check it out.

**Comment by kazzyUK** [comment]
Thats great.. and this what it looks like on the main screen.

![image](https://github.com/ellite/Wallos/assets/68235752/88f483fd-8114-4117-ab56-abe82874c8c9)

**Comment by ellite** [comment]
I increased it a little bit. There's some constraints because of the mobile layout.
It's on version 1.18.2
Keep in mind that some icons on the search really are that small, those will not be showing bigger.

Regards.
