### ISSUE TITLE
Import settings and subscriptions

### ISSUE THREAD

**Issue by cuizhenzhi** [ellite/Wallos#256]
I'm a huge fan of this project and deeply appreciate the hard work behind it. Recently, I've been contemplating migrating all services from my previous VPS to a new one. While exploring the functionalities, I found the option to export my subscription information in JSON format, which is quite useful. However, I faced a challenge as there seems to be no straightforward way to import the JSON file into the new server. Moreover, I noticed that the exported file doesn't contain details about my custom settings, which are crucial for the setup. These custom settings include payment methods, their priorities, subscription categories, and their respective sorting orders. Hence, I'd like to suggest the implementation of an import feature to streamline the migration process. Additionally, it would be incredibly helpful if the exported JSON file could encompass all pertinent information, including custom settings and associated images. I understand the complexity of this task but believe it would significantly improve user experience. Thank you for considering my feedback and keep up the fantastic work!

**Comment by ellite** [comment]
Hi. This should be doable. And is the goal eventually.

But you can just copy the two mounted folders (database and logos) to the new instance. Not as straightforward, but it should work.

Regards.

**Comment by cuizhenzhi** [comment]
Thank you. I will try this way first later.

**Comment by cuizhenzhi** [comment]
Hey there! Just wanted to drop you a quick note to say that I've successfully moved all my data over to the new server! It was a bit of a workaround, but I managed to do it by copying everything into the root directory of docker-compose.yml.
Thanks a bunch for your help along the way! Really appreciate it. Have a wonderful day.

**Comment by ellite** [comment]
Glad to hear 🙌

Enjoy.

**Comment by ellite** [comment]
Full backup and restore has been implemented on 1.23.0, regards.
