### ISSUE TITLE
[FEATURE REQUEST] Webhook support

### ISSUE THREAD

**Issue by zdzym** [ellite/Wallos#259]
Sometimes it's hard to use SMTP in some environments. I'd appreciate it if you can add webhook support (GET/POST to a URL when there is a notification). Really thank you for your time.

**Comment by ellite** [comment]
It's being worked on, but it's part of a bigger notification rework, so it will take some time.
Regards.

**Comment by PotatoYummy** [comment]
如果可以使用Bark直接推送通知到手机就完美了，期待ing
