### ISSUE TITLE
[FEATURE REQUEST] More information (category, paying user) in main screen

### ISSUE THREAD

**Issue by schlaggi** [ellite/Wallos#26]
Hello,

I really like the app so far 👌

As an extension, I would find it useful to be able to differentiate between the categories or the persons paying for something directly on the main screen. For example, you could give the option to show or hide these columns or let me select background colors per user or per category or something like that.
Alternatively, you could make each element collapsible to show everything that is not normally shown. Going into edit mode to see categories, who is paying for something or notes is kind of impractical in my opinion.

Keep on the good work!

**Comment by ellite** [comment]
Hi, thank you for the feedback. The collapsible cards is a great idea, and I've added it to my list.

**Comment by ellite** [comment]
This has been implemented: https://github.com/ellite/Wallos/commit/0cd6f649780bf19b541ec6a03b4040cc9b5a78db
