### ISSUE TITLE
Disable login or SSO support

### ISSUE THREAD

**Issue by gowtham1337** [ellite/Wallos#261]
I have Wallos hosted on docker behind a secure login page. I have to login to Wallos again after initially logging into my server. This is an unnecessary extra step.

The best solution for this is to support SSO providers. Portainer and a few other projects support this. However I understand that this is a big request in terms of complexity and code.

As an easy workaround, can we get the option to disable login completely and set a default user for a docker instance?

**Comment by Axe-l** [comment]
We neede mysql  more databases support .

**Comment by ellite** [comment]
@gowtham1337 hi, I've had this requested before. Disabling login should be easy enough, but I would prefer proper SSO implementation. Unfortunately I don't have time to look into it now. But it's on my list.

@Axe-l could you please elaborate?
SQLite should easily handle the type and amount of data that is generated even if someone has 1000 subscriptions.
Maybe "need" is not the correct word and that is why I'm confused.

Regards.

**Comment by ellite** [comment]
On version 2.4.0 you can now disable login on the admin page.
