### ISSUE TITLE
[Feature Request] Run Wallos in Subdirectory

### ISSUE THREAD

**Issue by fin444** [ellite/Wallos#276]
It would be great to have the option to run Wallos in a subdirectory, e.g. `https://example.com/wallos`

**Comment by ellite** [comment]
Hi. Nothing should prevent you from that.
Are you having any errors?

Regards

**Comment by fin444** [comment]
I might be missing an existing setting to do it, but when I try to access through `https://example.com/wallos` I get a 404. I tried using `X-Script-Name` but it had no effect. For reference, I am using the docker image 1.20.2, reverse proxied through Caddy.

**Comment by ellite** [comment]
I'm sorry. I never used caddy, don't know how it works.

Maybe someone has a similar setup and can assist.

**Comment by fin444** [comment]
Ok then, skipping the reverse proxy. If I try to `curl localhost:8282/wallos/login.php` I get `File not found.` but `curl localhost:8282/login.php` returns the login HTML.

**Comment by ellite** [comment]
Ah. I see. So you'd want the docker itself to have the app deployed on /wallos instead of / ?

That would be a strange setup.

It does not do that.

**Comment by fin444** [comment]
My bad, you are correct that it does work OOTB if you just strip the prefix. I made a mistake with my configuration.

**Comment by ellite** [comment]
No problem. 👍
