### ISSUE TITLE
Inaccurate payment time

### ISSUE THREAD

**Issue by shanyan-wcx** [ellite/Wallos#291]
My time zone is Asia/Shanghai. I set the payment date for a certain subscription to April 28th, but now it's already the 29th, and the next payment date will still be displayed as April 28th. Based on previous experiences, it seems like it will take two days to change the state.

**Comment by ellite** [comment]
Hi. Thank you for the report.
Do you have notifications enabled? If yes, are they being triggered at the correct time?

I'm not sure how timezones work on the containers, but I assume it must depend on the hosts time zone as well. Is the date and time on the host machine correct?

**Comment by shanyan-wcx** [comment]
This subscription does not have notifications enabled. Strangely, another subscription with notification enabled was reset at the correct time, and the notification time was also correct. The host machine time is correct.

**Comment by ellite** [comment]
So it seems date/time settings are not to blame.
Perhaps the cronjob responsible to update the dates failed to run or had some errors while running.
I'll have a look at the code and see if I find something that might be causing an error.
