### ISSUE TITLE
Webhook not working with Discord

### ISSUE THREAD

**Issue by TheGuardianLight** [ellite/Wallos#297]
I'm trying to set up a webhook notification via Discord but it doesn't seem to work.
Here's one of the links I used after creating the webhook on my Discord server: 
```
https://discord.com/api/webhooks/****/***
```

**Comment by ellite** [comment]
Hi. I redacted your URL since it seemed to have tokens in there.
Can you share more information on your settings?
Like the request method and payload so I can try it?

**Comment by TheGuardianLight** [comment]
Capture d'écran des paramètres :

![image](https://github.com/ellite/Wallos/assets/64707127/cedd1b5a-e35e-49d2-9529-c76027beb401)

**Comment by ellite** [comment]
Thanks for the info. I will have a look after work.
I am actually considering implementing Discord natively since it has a large user base.

**Comment by ellite** [comment]
Hi. I just released version 1.25.0 with native discord integration.
Would appreciate if you could test it.

Regards.

**Comment by TheGuardianLight** [comment]
Hi!
Sorry for the delay.
The native Discord integration does work.
However, I think that you need to set a default value of the "Webhook URL" field because otherwise it puts the following error:
![image](https://github.com/ellite/Wallos/assets/64707127/b0fc0688-7999-4f07-930e-570c0ef7cea4)

**Comment by ellite** [comment]
Just released 1.25.1 to fix that.

**Comment by TheGuardianLight** [comment]
Perfect, thanks for your reactivity!

**Comment by ellite** [comment]
Glad it's working.
Thank you for testing.
