### ISSUE TITLE
[Feature Request] Pay off credits, enter credit rates

### ISSUE THREAD

**Issue by terraboss** [ellite/Wallos#299]
Not all regular payments are the same. Assuming you have an expensive purchase made, a mortgage or something else to pay off, you usually have an installment plan, the repayment amount and duration. It would be great if this could also be entered and managed in “Wallos”. Even if you pay off the credit early or in case the rates will change in the meantime. 

Yes, it's a bit of a mathematical challenge. But I think this feature would greatly enrich the software. 

Tanks in advance!

**Comment by ellite** [comment]
Hi. Thank you for the suggestion.
This is a bit out of the scope of the app for the moment and it's not planned.
Might revisit it later.
