### ISSUE TITLE
Feature Request - Deactivate subscriptions

### ISSUE THREAD

**Issue by Appoxo** [ellite/Wallos#31]
I think an option to pause a subscription would be useful to not set it all up again.  
Could be used in the future for data collection for nice graphs

**Comment by ellite** [comment]
Hi. I will add it to my list of features to add.

**Comment by Joshndroid** [comment]
Yes please I would like this as well :)

**Comment by ellite** [comment]
It's implemented since 1.5
Regards.

**Comment by Joshndroid** [comment]
Thanks @ellite
