### ISSUE TITLE
Discord notification not working

### ISSUE THREAD

**Issue by TheGuardianLight** [ellite/Wallos#318]
Although configuring and sending test messages via webhook to my discord server works, automatic notifications don't seem to work.

(Previous issue related to Discord : #297 )

**Comment by ellite** [comment]
Hi. Can you do:

`docker exec -it wallos sh`

And once inside the container see if there's any useful information on

/var/log/cron/sendnotifications.log

You can do

`cat /var/log/cron/sendnotifications.log`

Thanks.

**Comment by ellite** [comment]
Ah, right. I should find a way to make those persistent.
Maybe you can create a dummy subscription expiring in however many days you have the notifications set in the settings and run inside the container:

`php /var/www/html/endpoints/cronjobs/sendnotifications.php >> /var/log/cron/sendnotifications.log`

then you can see the logs with

`cat /var/log/cron/sendnotifications.log`

**Comment by TheGuardianLight** [comment]
There is the result :

```
Email Notifications sent<br />
Fatal error: Uncaught Error: Call to undefined function translate() in /var/www/html/endpoints/cronjobs/sendnotifications.php:216
Stack trace:
#0 {main}
  thrown in /var/www/html/endpoints/cronjobs/sendnotifications.php on line 216

```

**Comment by TheGuardianLight** [comment]
What's more, I can see that the notification on Gotify isn't working either, even though the send test is working perfectly.

**Comment by ellite** [comment]
This is very helpful. Thanks. 
I'll try to find the source and fix it.

**Comment by ellite** [comment]
Should be fixed on 1.27.1
Regards.

**Comment by TheGuardianLight** [comment]
Hi!
It's working properly now!
However, I've noticed that on the message sent via the Discord integration, the same message appears twice:

![image](https://github.com/ellite/Wallos/assets/64707127/1cd2c7e2-bf9c-4795-a002-9e05e1a5d0af)

**Comment by ellite** [comment]
I'll check it out.

**Comment by ellite** [comment]
The double message was fixed on today's release.
Regards.
