### ISSUE TITLE
Feature Request: Able to pick notifications earlier than 7 days

### ISSUE THREAD

**Issue by TheMarf** [ellite/Wallos#325]
Hello!  I saw a number of posts requesting the ability to set multiple notifications and while I agree that would be useful I have a different request.

I'd like to be able to get a notification up to 30 days prior to a subscription expiration/renewal.  I was wondering why I got an email today from a service about renewal but hadn't seen one from Wallos yet - but then I realized the max I can set is 7.

Marf

**Comment by ellite** [comment]
Implemented o 1.29.0.
Regards.
