### ISSUE TITLE
Allow me to add Wallos to my Wallos by enabling GitHub Sponsorship

### ISSUE THREAD

**Issue by oregonpillow** [ellite/Wallos#332]
Awesome project! Absolutely love this tool and would love to support it.  If you could enable sponsorship that would be great. I'm sure many others would appreciaite it as well.

**Comment by ellite** [comment]
Hi. Thank you for your words.

I believe I have to have a registered business to enable sponsorships.
Also, I'm not looking to profit from this project. Just want to give something back to the community.

Regards <3

**Comment by oregonpillow** [comment]
You're a horrible person, take my money 😁. Ok no worries, very kind of you. I'll try and contribute at some point to say thanks. 

Just as a FYI, I'm pretty sure you don't need to be an organisation to accept donations. 

Consider also https://ko-fi.com/ or https://buymeacoffee.com/ 

Best,
Tim

**Comment by ellite** [comment]
Thank you.
Have a great day.

**Comment by ellite** [comment]
Hi. I finally gave it a look and enabled sponsorships.
Regards.
