### ISSUE TITLE
[Feature Request] Set longer reminder time

### ISSUE THREAD

**Issue by z499738316** [ellite/Wallos#333]
The services subscribed by the company require application and renewal one month in advance, but the current reminder mechanism is up to 7 days. Can the author support setting a longer time

**Comment by flinthamm** [comment]
I was just about to request the same feature, perhaps there could be a custom option for maximum flexibility with the units in days. Some of our subscriptions require a 60 day notice before cancellation, so this is a must.

**Comment by ellite** [comment]
Hi. 

The current implementation with only one choice for how many days before to notify would not make sense anymore. 
So I will have to implement different number of days per subscription.
I've added it to my list. But might take some time.

Regards.

**Comment by ellite** [comment]
Available on 1.29.0
