### ISSUE TITLE
Getting "Error Failed to load subscription" upon clicking the edit button

### ISSUE THREAD

**Issue by daniel-l** [ellite/Wallos#337]
Running the latest docker image.

When clicking the edit button of a subscription in the lower right corner the following message appears:

```
Error 
Failed to load subscription
```
 
The edit windows does not appear. 
This happens on 28 of 38 subscriptions. 
These subscriptions cannot be edited/deleted.

**Comment by ellite** [comment]
Hi, I'm pretty sure the error is the same as on the other report. A fix is now live on 1.29.1
Would appreciate if you could update and report back if both issues are fixed. Thanks.

**Comment by daniel-l** [comment]
Yep, that's fixed again. Subscriptions can be edited, added and deleted without any issue.
Thanks for the ultra fast response!

**Comment by ellite** [comment]
Perfect. You're welcome.
Thank you for reporting it.

Regards.
