### ISSUE TITLE
Can only choose a maximum of 31 days

### ISSUE THREAD

**Issue by fsmeets84** [ellite/Wallos#342]
I got a subscription where I have to pay every 180 days. However the maximum number of days I can choose is 31.
For now I have set it to 6 months, however this equals to 182,5 days, therefore my subcription is out of sync.

**Comment by ellite** [comment]
next version will  change the max frequency from 31 to 366.
Regards

**Comment by ellite** [comment]
Hi, on version 2.2.0 you can now choose up to 366 days. Regards.
