### ISSUE TITLE
[Feature Request] Backup Filename Change

### ISSUE THREAD

**Issue by My-Random-Thoughts** [ellite/Wallos#347]
The current backup filename saved is `backup.zip`.

A more descriptive name would be much better and include the date so multiple backups can be taken and organised.

Something like: `Wallis-Backup-yyyyMMdd-hhmm.zip`

**Comment by ellite** [comment]
Will be part of the next release.
Regards.

**Comment by ellite** [comment]
It's live with 2.2.0
