### ISSUE TITLE
[Feature Request] - Integration with Plaid API

### ISSUE THREAD

**Issue by mgriffin13** [ellite/Wallos#356]
[Plaid](https://plaid.com/docs/) is a service that will allow applications to integrate with some financial institutions without sharing credentials. Integrating with this service would allow Wallos to retrieve real-time transaction data from linked credit cards and thus allow Wallos to auto-discover recurring charging and thus potential subscriptions.

This integration doesn't necessarily need to rely on a centralized service--I think that individuals could sign up for their own developer account and thus could use their own API keys for the integration. Wallos just needs the back-end logic to deal with the influx of data.

https://plaid.com/docs/quickstart/#introduction

**Comment by ellite** [comment]
Hi, thank you for the suggestion.
This is not on the plans for now. I might revisit this idea later.
