### ISSUE TITLE
[FEATURE REQUEST] - Stats per category

### ISSUE THREAD

**Issue by Fyreek** [ellite/Wallos#36]
Would be useful to see statistics for every category separately.

Maybe via a dropdown above the normal statistics.

**Comment by ellite** [comment]
I added some statistics recently.
What kind of statistics would you be interested in?
Thanks.

**Comment by Fyreek** [comment]
I meant the current stats page but with a filter above where you can choose a category.
Then show the same stats as before but only for items that are in the selected category.

Like in this screenshot:

![grafik](https://github.com/ellite/Wallos/assets/13890839/bc4d7bb7-f9f4-4172-8182-1b8b2be9a0cd)

So if you chose Entertainment it would only show the stats for every item in the Entertainment category.

**Comment by ellite** [comment]
Ah. I see. 
I will add it to my list, but might take a while until I get to implement it.

**Comment by ellite** [comment]
Feature added on 12.0.0
Regards.
