### ISSUE TITLE
[BUG] Numbers on the statistics page are incorrect

### ISSUE THREAD

**Issue by jamess60** [ellite/Wallos#362]
Just setup Wallos for the first time. Set my users default currency to GBP, and all subscriptions bar one to GBP. 
I added an APILayer API key.

My most expensive subscription is £450 per month. On the most expensive subscription section of the statistic page, it identifies this subscription as £528.66. It calculates my monthly total at £608.64, but when using a calculator, it adds to £513.54.

It also seems impossible to delete the Euro currency despite no users being set to Euro as default and no active subscriptions in euros?

**Comment by jamess60** [comment]
Bump - any updates?

**Comment by ellite** [comment]
Hi James. I didn't have a chance to look at it yet. I'm currently on holidays, but I will try to have a look if I have some time.

**Comment by ellite** [comment]
I tried it, and also looked at the code.
The only reasons to not be able to delete EUR are:
- Is set as main currency
- Is in use in a subscription

Can you please check your subscriptions if any s set in EUR?
If you have this setting enabled `Always convert and show prices on my main currency (slower)` it will show them all in GBP on the dashboard, so you would have to individually edit every subscription and check which currency it is using.

Regards.

**Comment by jamess60** [comment]
Hi

Apologies for interrupting your holiday and thanks for the quick update! :) 

I did indeed have one subscription still set to euro (missed this as having Always convert enabled showed a £ symbol). After this, I was able to remove the euro currency. 

The statistics now appear correct too :) 

Think this was a layer8/pebcak issue - sorry for the bother
