### ISSUE TITLE
Bug: Adding SVGs 

### ISSUE THREAD

**Issue by SchaffRita** [ellite/Wallos#366]
**Steps to reproduce**
1. Start Wallos with the official instructions in a Docker container
2. Add a new subscription
3. Set the title, price, next payment
4. Click on **Upload Logo**
5. Select an svg file, e.g. this
![Sublime Text](https://github.com/ellite/Wallos/assets/50463942/914f3acf-da41-4bdd-8366-268b1913316f)
6. Assert that it is visible in the UI
7. Save the subscription

✔️ **Expected behavior**: the logo is displayed next to the subscription.
❌ **Actual behavior**: the logo is not displayed next to the subscription. Checking the subscription again shows that the logo was not changed at all.

ℹ️ Additionally, I found some subscriptions randomly disappeared while testing this - I could not reliably reproduce this but it is good to keep in mind.

https://github.com/ellite/Wallos/assets/50463942/31458df9-cb54-4a0f-92e2-d4bb0b2c877b

**Comment by ellite** [comment]
Hi. I removed svg support due to a vulnerability. Haven't figured out a solution around it yet.

**Comment by ellite** [comment]
Hi. I re-added SVG support. Regards.
