### ISSUE TITLE
Feature Request: Add a grid view

### ISSUE THREAD

**Issue by SchaffRita** [ellite/Wallos#368]
Right now the only available view is the list view.
I think it would be a cool feature if you could add a grid view.
Example:
![](https://miro.medium.com/v2/resize:fit:2000/0*QpcPkyD2wab4jSiv)

**Comment by ellite** [comment]
Hi. I gave it a quick try and couldn't find a layout that would look good or even make sense on how to show the details of the subscription.
I might revisit this later. But for now it's not planned
