### ISSUE TITLE
Feature Request: Settings UI improvement

### ISSUE THREAD

**Issue by SchaffRita** [ellite/Wallos#369]
There are many settings already and if not all, but most would work a lot better with another view.

- Create tabs on the left for each section ([random example](https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/50003247907/original/OflxZ5IbeX74n8DpkFi5QqdzzTpLoVplnQ.png?1624506649))
- Make sections collapsible ([simple example](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_collapsible))

**Comment by ellite** [comment]
Hi, this is not planned for now.
Thank you for the suggestions.
