### ISSUE TITLE
Cannot send email / Test 

### ISSUE THREAD

**Issue by DcryptedCA** [ellite/Wallos#37]
Tried to setup the email settings but when I press the test button it causes Wallos to freeze up (504 gateway error) and then it does nothing (sometimes I get the "Error sending notification" pop-up"). I confirmed my SMTP settings are correct.

**Comment by ellite** [comment]
Some services won't allow just any From address, for those cases I added one more field on the SMTP settings. https://github.com/ellite/Wallos/commit/0b6246b09db6a9e1634d300cb0f89d0f9de241ea
Hopefully this fixes it.

**Comment by devzwf** [comment]
Please pull the main tag and retest.
be aware that i think only server with TLS works at the moment.

**Comment by TheAnachronism** [comment]
I've tested it out and all messages and logs point to it successfully sending something, but I never receive anything.

**Comment by devzwf** [comment]
check at you smtp is the mail did not get block.
happen if they think it is spam.

**Comment by devzwf** [comment]
did you have any update ?

**Comment by DcryptedCA** [comment]
> Some services won't allow just any From address, for those cases I added one more field on the SMTP settings. [0b6246b](https://github.com/ellite/Wallos/commit/0b6246b09db6a9e1634d300cb0f89d0f9de241ea) Hopefully this fixes it.

This resolved my issue.
