### ISSUE TITLE
Bug: Paid by does not show new user

### ISSUE THREAD

**Issue by SchaffRita** [ellite/Wallos#370]
Use case: there are 2 users, John and Rita. John is paying for Netflix, while Rita is paying for Disney+.
This could be set at **Paid by**.

We can add multiple users
![image](https://github.com/ellite/Wallos/assets/50463942/84f46d86-0e04-474b-a15f-2419d48077e6)
but the other users are not visible in the dropdown and thus, they cannot be added to a subscription.
![image](https://github.com/ellite/Wallos/assets/50463942/0e481164-c59e-46af-ab48-e9e3c606ccde)

What is exactly the expected behavior in this case?
Please let me know in case you want steps to reproduce this scenario.

**Comment by ellite** [comment]
Hi.

That's not a bug. 
The different accounts are not connected.

I might explore a way to connect accounts in the future.

The "paid by" uses the household members in the settings.

Regards.
