### ISSUE TITLE
[FEATURE REQUEST] Calendar 

### ISSUE THREAD

**Issue by samuele794** [ellite/Wallos#38]
I propose as a feature the possibility of seeing renewals on a calendar and potentially supporting export to Google Calendar or similar calendars

**Comment by compgeniuses** [comment]
WOuldnt it be interesting to have integration to something like Caldav or even cal.com on this aspect

**Comment by ellite** [comment]
I'll add it to my list to have a look. Not promising that it would be implemented though!

**Comment by compgeniuses** [comment]
Looking inot it would be a start, Implemnting a Full fledged calendar is hard, and would not make sense.
but Implementing a Caldav integration of sorts, would enebale someone to subscribe to the relevant calenda for bills and have the view in their favorite calenda app

**Comment by ellite** [comment]
Calendar view is complete. Export will (hopefully) come next.
