### ISSUE TITLE
[BUG] Cronjob `endpoints/cronjobs/updateexchange.php` does not take in account apilayer key

### ISSUE THREAD

**Issue by peterbuga** [ellite/Wallos#380]
The entire file assumes that **only** fixer.io key exists and does not take in account the `provider:1` aka apilayer key might be configured instead.

https://github.com/ellite/Wallos/blob/main/endpoints/cronjobs/updateexchange.php#L42

**Comment by ellite** [comment]
Thank you. I'll have a look.

**Comment by peterbuga** [comment]
@ellite I see you fixed the bug, thank you! I will close the issue 👍

one thing to mention, please move this line https://github.com/ellite/Wallos/pull/381/files#diff-f357b02eae6f5a67979aad572f3ffe45c1ae4fe5a31369487eb3968d4ad7de79L78 at the end of the script otherwise you close the db connection prematurely and you cannot complete proper looping here (especially if there are more users ) https://github.com/ellite/Wallos/pull/381/files#diff-f357b02eae6f5a67979aad572f3ffe45c1ae4fe5a31369487eb3968d4ad7de79L10

**Comment by ellite** [comment]
Thanks. I will check after work today.
