### ISSUE TITLE
Images reset after container update

### ISSUE THREAD

**Issue by electric-m** [ellite/Wallos#388]
Hey t here,

at the moment, whenever I pull the most recent container and recreate, the images are being replaced by a placeholder, and I have to reset them all manually:
<img width="328" alt="SCR-20240614-pgfq" src="https://github.com/ellite/Wallos/assets/40071240/ca0bbe1b-00fc-495d-84a8-e7e4a6b5fbc8">

**Comment by ellite** [comment]
Hi. Are you mapping the path for the logos correctly?

`-v /path/to/config/wallos/logos:/var/www/html/images/uploads/logos`

**Comment by ellite** [comment]
Hi. Any news on this issue?

**Comment by electric-m** [comment]
> Hi. Any news on this issue?

Sorry for not answering, I completely missed your reply.
Meanwhile, I solved it like this:

I deleted the subscription and recreated them completely.
I don't know why, but now, they survive e container recreation/update, whilst keeping the logos.

I did not change anything in the Compose file. Logos folder was already mounted correctly before.

**Comment by ellite** [comment]
Hi. Thank you for the reply.
No idea what it could have been. 
Glad it's working now.
Regards.
