### ISSUE TITLE
[Feature request] Adding ntfy.sh as Notification provider

### ISSUE THREAD

**Issue by electric-m** [ellite/Wallos#389]
Hey there,

might be worth looking at, since the service can be self-hosted and is used by many homelab users already (see example integrations):

https://docs.ntfy.sh/integrations/

**Comment by ellite** [comment]
Hi. Ntfy was added a few updates ago. Maybe you're using an old version of Wallos and need to update.

![image](https://github.com/ellite/Wallos/assets/3831180/b6125054-2692-45c6-9a97-b95c364ea73d)

**Comment by electric-m** [comment]
Sorry, you are absolutely right. Nonetheless I do get the error for my that "the string does not match the expected pattern".
I defined my ntfy url and the topic.
Nothing for custom headers.

**Comment by ellite** [comment]
Thanks. I'll try to figure out what the issue might be.

**Comment by electric-m** [comment]
> Thanks. I'll try to figure out what the issue might be.

The same error applies to E-Mail, which definitely uses the correct cress. Tired in another similar app.

**Comment by steffenrapp** [comment]
I had the same error in ntfy. A custom header for authorization that looks like this works but the error still appears even if the notification arrives.

{ "Authorization": "Basic xyz" }

**Comment by ellite** [comment]
Hopefully it is fixed with 2.5.1.

**Comment by electric-m** [comment]
@ellite Hey there,

it is still not clear to me, if this is (still) a bug, or just a misconfiguration.
I tried several options,alo including the Bas64 encoded user/pass in the url string.

Also the header option, but I don't understand how the header should look in this setting, as there are multiple formats, that Ntfy defines (JSON, Curl, http and so on.)

<img width="508" alt="SCR-20240621-oihq" src="https://github.com/ellite/Wallos/assets/40071240/0a28723f-da41-4210-8a5e-dfc827df0623">

On example I tried (with my actual data obviously)
<img width="780" alt="SCR-20240621-oigm" src="https://github.com/ellite/Wallos/assets/40071240/98ee0bcd-4988-448f-ac9f-3def5678f8bb">

**Comment by electric-m** [comment]
@ellite Oops, never mind, now it is working, I missed the curly braces!

Header should look at least like:
`{"Authorization": "Bearer your-token-here"}`

**Comment by ellite** [comment]
Ah yes, it sends exactly what's on the field.
Glad it's working.
