### ISSUE TITLE
[FEATURE REQUEST] Change view (number of columns)

### ISSUE THREAD

**Issue by bonny1992** [ellite/Wallos#39]
It would be nice being able to customize the number of columns of the main view.
(a slider maybe?)

Or could be done by grouping them by month/year, keeping them in order.

**Comment by ellite** [comment]
Sorry, I don't think I understand. Could you please elaborate?
Thanks.

**Comment by bonny1992** [comment]
Oh if I may make an example with another piece of software: Tubearchivist.
![image](https://github.com/ellite/Wallos/assets/1154368/88f242d1-38c2-4766-8287-efb557f49592)
As you can see those buttons I circled change how the view of the home page is.
The plus and minus sign change the number of the columns.
The "windows logo" looking one changes to "cards" like the screenshot.
The "stripes" one changes to this:
![image](https://github.com/ellite/Wallos/assets/1154368/ea1e9d66-0ded-40f1-a648-33763c5625b6)

What I mean is a way to change the columns something like the plus and minus sign from Tubearchivist, maybe inside the settings page.
