### ISSUE TITLE
Feature request: Clone an existing subscription

### ISSUE THREAD

**Issue by programmer24601** [ellite/Wallos#391]
It'd be really useful to be able to clone an existing subscription. This is especially useful when you've selected a custom logo for a subscription and you have a set of subscriptions that should only differ in one respect, but should otherwise match for everything else.

This could be achieved by adding another button next to "Edit subscription", should as "Clone subscription" (or it could be hidden in a `...` context menu) for each subscription in the main list. If the context menu option is favoured that could also host the "Delete subscription" button, which is currently only accessible via the Edit subscription form.

**Comment by ellite** [comment]
Hi. Thank you for the suggestion.
The cloning part is already on my ToDo list. But I haven't started implementing it yet.
The second part it's actually a great idea, Since I haven't figured how to actually present all this options. I might take that route.

**Comment by ellite** [comment]
Same as https://github.com/ellite/Wallos/issues/358
