### ISSUE TITLE
Fatal Error in Calendar View (version 2.6.0)

### ISSUE THREAD

**Issue by YoSafeguard** [ellite/Wallos#401]
Hi!

When viewing the Calendar view, an error occurs:

`Fatal error: Uncaught Error: Call to undefined function cal_days_in_month() in /var/www/html/calendar.php:82 Stack trace: #0 {main} thrown in /var/www/html/calendar.php on line 82`

**Comment by ellite** [comment]
Hi. Thank you. It seems that my local environment has the calendar library loaded and the docker image does not.
Just pushed a fix (hopefully).
Will release it soon.
Regards.
