### ISSUE TITLE
Feature request: Light/Dark Mode based on system settings

### ISSUE THREAD

**Issue by steffenrapp** [ellite/Wallos#405]
Many apps and Web apps have an option to use the Light/Dark Mode based on system settings. In Wallos you can only manually switch between the two modes. It world be great to have a third mode for automatic switching based on the OS's setting.

**Comment by ellite** [comment]
Hi. That's now available on 2.8.0
https://github.com/ellite/Wallos/releases/tag/v2.8.0

Regards.
