### ISSUE TITLE
[FEATURE REQUEST] Add one-time payments

### ISSUE THREAD

**Issue by DominicBeer1804** [ellite/Wallos#42]
It would be great if you could also record “normal payments” with it.
So no billing cycle. Just the one-time payment in the supermarket, for example.
To make a distinction, you could also place an additional button on the dashboard:

![Snag_624387fa](https://github.com/ellite/Wallos/assets/129688022/930360a0-8056-47d3-b3c9-4f395bbcb651)
![Snag_62444f23](https://github.com/ellite/Wallos/assets/129688022/2009eed3-c212-4345-b113-ad458685efc7)

**Comment by bonny1992** [comment]
Wouldn't this be for a more budgeting/finance app though, instead of a subscription tracker?

**Comment by ellite** [comment]
I agree with with @bonny1992 . It's not the direction Wallos will go, at least not for now.
But thank you for the suggestion.

**Comment by DominicBeer1804** [comment]
Ok.
