### ISSUE TITLE
Bug: Cannot add images on v2.14.1

### ISSUE THREAD

**Issue by Eidenz** [ellite/Wallos#430]
Any attempt to add an image, whether using the search or manual will display an error and the network response ending up being:
`Fatal error: Uncaught Error: Call to a member function bindParam() on bool in /var/www/html/endpoints/subscription/add.php:212 Stack trace: #0 {main} thrown in /var/www/html/endpoints/subscription/add.php on line 212`

![image](https://github.com/ellite/Wallos/assets/27901016/d15975ec-a600-416d-9a56-17711f827da3)

**Comment by ellite** [comment]
Thanks for the report. A fix is being deployed now.

**Comment by Eidenz** [comment]
Pulled new version, still get the error for manual images:
![image](https://github.com/ellite/Wallos/assets/27901016/0539fc5b-4b75-4fc1-bfa8-45f51b2ed41e)

But this time with this response:
`Fatal error: Uncaught TypeError: imagecopyresampled(): Argument #2 ($src_image) must be of type GdImage, bool given in /var/www/html/endpoints/subscription/add.php:132 Stack trace: #0 /var/www/html/endpoints/subscription/add.php(132): imagecopyresampled(Object(GdImage), false, 0, 0, 0, 0, 87.19723183391, 42, 1200, 578) #1 /var/www/html/endpoints/subscription/add.php(186): resizeAndUploadLogo(Array, '../../images/up...', 'Patreon', Array) #2 {main} thrown in /var/www/html/endpoints/subscription/add.php on line 132`

But works with images using search.

**Comment by ellite** [comment]
Thank you for testing and reporting back. I can't reproduce it. Might be image specific. Could you upload the image here so I can try to figure it out?
Thanks.

**Comment by Eidenz** [comment]
This is the picture below. Funny enough, if I actually re-save it (no matter the extension), it will then work. But pulling it straight from the webpage creates the issue mentioned previously.

![newpatreon](https://github.com/ellite/Wallos/assets/27901016/84a9b923-9f50-4512-a1e9-05808a9890f4)

**Comment by ellite** [comment]
This image is a webp renamed to png.
And that causes the issue when `imagecreatefrompng `runs instead of `imagecreatefromwebp`
Simply renaming it to a .webp makes it work as intended.

**Comment by Eidenz** [comment]
Oh weird, so I guess right click > save image sometimes fails. Explains why saving it back fixes it.
