### ISSUE TITLE
Bug: Cannot log in after registering first user - Incorrect password error

### ISSUE THREAD

**Issue by BloodAkatsuki** [ellite/Wallos#444]
After registering the first user during the initial installation of Wallos, I am unable to log in with the registered password. The system reports that the password is incorrect.

Steps to Reproduce:

    Clone the Wallos repository.
    Build and run the Docker container as per the provided instructions.
    Register the first user during the initial setup.
    Attempt to log in with the registered credentials.

Expected Behavior:
Users should be able to log in with the credentials they registered during the initial setup.

Actual Behavior:
The system reports that the password is incorrect, preventing the user from logging in.

**Comment by ellite** [comment]
Hi. Do you have any capital letter on the username? if so, try with the user name in all lower case letters.
Otherwise I would just delete the database on the mounted volume and restart the container and try again. Maybe some typo happened somewhere.

**Comment by BloodAkatsuki** [comment]
Hi,

After a fresh pull of the docker image and using the username in all lowercase letters, it worked. Thanks for the suggestion!

Best regards,
