### ISSUE TITLE
Sort alpha numerically

### ISSUE THREAD

**Issue by dhjackal** [ellite/Wallos#448]
Wondering if you can add a small (aren't they all) update / enhancement. I order my subscriptions 1, 2, 3 etc so I can keep a totals (perhaps something else that could be considered) column. However the sort list isn't alpha numerical.....when sorted on name it runs 1,10, 11, 12, 2 3 true alpha numerically but not sequentially.

**Comment by ellite** [comment]
Hi. 
Oh, good point. I'll check that out.

**Comment by dhjackal** [comment]
Super, smashing.....great

**Comment by ellite** [comment]
New sorting method available on 2.19.0
Regards.

**Comment by dhjackal** [comment]
Got it and it's all working. Thanks and apologies for the delay in replying....I'm a relative GitHub noob
