### ISSUE TITLE
[FEATURE REQUEST] Progressive web app

### ISSUE THREAD

**Issue by Forcide** [ellite/Wallos#45]
It would be a nice feature to be able to install the website as an app on Android and iOS.

[Heroku blog about PWA](https://blog.heroku.com/how-to-make-progressive-web-app)
[Firefox PWA explanation](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps)

(Thanks for making Wallos, great piece of software!)

![signal-2023-11-14-222134_002](https://github.com/ellite/Wallos/assets/9076918/2b81f1e4-49df-4dc2-9ea0-dd081038d072)

**Comment by ellite** [comment]
Thanks. I will investigate when I have some free time.

**Comment by ellite** [comment]
It should be working on 1.8.0
Regards

**Comment by ellite** [comment]
It's live with 1.9.0 👌
