### ISSUE TITLE
[BUG] Delete button, on "edit subscription modal" doesn't work

### ISSUE THREAD

**Issue by GabrielRozendo** [ellite/Wallos#459]
Wallos v2.19.1
Tested on 
- Desktop: Safari 17.5 and Arc 1.51 (Chromium Engine Version 126.0.6478.127)
- Mobile: iPhone Safari

After the test in #458 I've tried delete the testing subscription from modal view, in "delete button" but nothing happens, checked the console and there was the error:
```
[Error] TypeError: event.stopPropagation is not a function. 
(In 'event.stopPropagation()', 'event.stopPropagation' is undefined)
	deleteSubscription (dashboard.js:174)
	onclick (Script Element 8:1)
```

![CleanShot 2024-07-15 at 23 15 17](https://github.com/user-attachments/assets/a36ffc76-af5c-4f9c-9437-7ad6fec24da3)
![CleanShot 2024-07-15 at 23 16 13](https://github.com/user-attachments/assets/a8f3506a-6041-486d-be1e-4d06d62bf12d)

no problem on delete from dashboard view (instead step 2)!

**Comment by ellite** [comment]
Thanks for the report.
A fix has been released.
