### ISSUE TITLE
Telegram / Discord Notifications not working

### ISSUE THREAD

**Issue by xinput** [ellite/Wallos#462]
Hello, 

I tried configuring notifications. Tested Discord and Telegram, but Test Notification does not work.
In the COntainer Logs I get following output:
`127.0.0.1 -  17/Jul/2024:08:14:07 +0200 "POST /endpoints/notifications/testdiscordnotifications.php" 200`

When doing `cat /var/log/cron/sendnotifications.log` I get the follwing output:
```
`For user: user <br />Notifications are disabled. No need to run.<br />
2024-07-17 06:15:13<br />`
```

Any Ideas what's going on here?

Thanks in advance

**Comment by ellite** [comment]
Hi, sorry. I never got to this. 
Did you find a solution?

**Comment by xinput** [comment]
Hey, no problem! I honestly did not debugged it further as I moved all my notifications to ntfy, which works well. That's why I marked this as closed. :)

**Comment by ellite** [comment]
All right. Thanks. I'll still try to check it when I have some time
