### ISSUE TITLE
[FEATURE REQUEST] Update Notification

### ISSUE THREAD

**Issue by TheGuardianLight** [ellite/Wallos#468]
At the moment, in order to know if an update is available, we have to connect to the project's Github repository and compare the version of Wallos currently installed with the latest version available on the repository.

I think an update checker tool in Wallos could simplify the checkout process and display a notification or slip that an update is available with maybe a link to the new release.

I've already done a similar system in a bash script for another piece of software if that helps (for checking if a new release is available).

**Suggested warning system :**

- Via an alert banner on the software's home page
- By e-mail
- Via one of the configured webhooks

**Exemple of idea :**

![image](https://github.com/user-attachments/assets/8b3c1e29-9da0-4870-89e2-438614782f51)
(Made with Figma)

**Comment by TheGuardianLight** [comment]
Regarding the bash script I made, we could imagine something like this: 

```bash
#!/bin/bash

# Defining the GitHub repository
repository="ellite/Wallos"

# Get information on the latest version
release_data=$(curl -sSL "https://api.github.com/repos/$repository/releases/latest")

# Extract the tag name (the latest version)
latest_release=$(echo $release_data | jq -r '.tag_name')
version_number=${latest_release#v}

# Read the current version of Wallos from a file
current_version=$(cat /data/wallos.txt)

# Compare versions
if [ "$version_number" == "$current_version" ]; then
    echo "There is not new version."
    exit 0
elif [ "$(printf '%s\n' "$version_number" "$current_version" | sort -V | head -n1)" != "$version_number" ]; then
    echo "A new version is available : $version_number"
fi
```

For information, in my script I use a file that contains a version number for testing purposes, so here are its contents: 

```text
2.19.0
```

I hope this would help you

**Comment by ellite** [comment]
Hi, Version 2.21.0 includes a setting on the admin page to enable the notifications. But for now only the banner on the dashboard is Implemented. I will check later if I will add any other notification method.
