### ISSUE TITLE
SMTP JSON Error

### ISSUE THREAD

**Issue by andyhuggs** [ellite/Wallos#472]
Trying to setup email notifications and I keep getting this error when testing:

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

The test email was working a couple days ago when I first set everything up now it keeps giving me that error.

**Comment by ellite** [comment]
Hi. Can you please open the Developer Tools, go to the network tab and click the test button with the tab open?
You should be able to see the failed request. If you click it you should be able to go the response tab and see the actual error message.
Then please copy the error message and paste it here.

Thanks.

**Comment by andyhuggs** [comment]
Here you go:

Fatal error: Uncaught PHPMailer\PHPMailer\Exception: The following From address failed: wallos@wallosapp.com : MAIL FROM command failed,From address is not one of your addresses ,550,5.7.0SMTP server error: MAIL FROM command failed Detail: From address is not one of your addresses SMTP code: 550 Additional SMTP info: 5.7.0 in /var/www/html/libs/PHPMailer/PHPMailer.php:2034 Stack trace: #0 /var/www/html/libs/PHPMailer/PHPMailer.php(1682): PHPMailer\PHPMailer\PHPMailer->smtpSend('Date: Wed, 31 J...', 'This is a test ...') #1 /var/www/html/libs/PHPMailer/PHPMailer.php(1516): PHPMailer\PHPMailer\PHPMailer->postSend() #2 /var/www/html/endpoints/notifications/testemailnotifications.php(69): PHPMailer\PHPMailer\PHPMailer->send() #3 {main} thrown in /var/www/html/libs/PHPMailer/PHPMailer.php on line 2034

**Comment by andyhuggs** [comment]
I just put the optional from email address the same as the smtp username and the test email seem to work this time. Thanks!

**Comment by ellite** [comment]
Yes. That was the issue. Glad it's working.
