### ISSUE TITLE
[PHP Warning] PHP depreciation warning

### ISSUE THREAD

**Issue by TheGuardianLight** [ellite/Wallos#477]
Hi !

I've upgraded to 2.21.0 and PHP tells me this on the "admin.php" page: 

```
Deprecated
: version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated in
/var/www/html/admin.php
on line
241
```

This is obviously displayed because I've enabled the option in the PHP settings.

**Comment by ellite** [comment]
Hi. Thank you for the report.
Yes, I have noticed but unfortunately I can't fix it at the moment. Only later today I will have time.
In the meantime you can run ip:port/endpoints/cronjobs/checkforupdates.php
Should also go away once the cronjob runs. (Every 6 hours)
Regards.

**Comment by TheGuardianLight** [comment]
Thanks ! I will wait for the cron to run ;)

**Comment by ellite** [comment]
v2.21.1 released and should fix that warning.

**Comment by TheGuardianLight** [comment]
Yup, it's fixed
