### ISSUE TITLE
[BUG] Profile picture not uploading

### ISSUE THREAD

**Issue by TheGuardianLight** [ellite/Wallos#478]
I noticed that you could add a custom profile image.

However, I've noticed that it doesn't work (not for me anyway) and I don't get any errors.

**Comment by ellite** [comment]
Hi. I can'r reproduce the issue.
Does that happen with every image or just a specific one?

Can you please open the developer tools on your browser, go to the network tab and try to add the image? 
Then click on the request save_user.php and go to the response tab.
Does it show any error? Thanks.

**Comment by TheGuardianLight** [comment]
I have nothing...

There is a screenshot and a vid : 

![image](https://github.com/user-attachments/assets/c8e4c4fb-e8b6-4726-92f9-64d883c153c8)


https://github.com/user-attachments/assets/a8436147-74d9-4451-93fb-647e286bac71

**Comment by ellite** [comment]
Oh. Doesn't the file selection window show at all?

**Comment by TheGuardianLight** [comment]
The Windows selection window opens fine. OBS just didn't capture it on the video.

Here's a screenshot of the erroneous code: 

![image](https://github.com/user-attachments/assets/683c0461-f904-428e-8c03-68dfaacfc00a)

**Comment by ellite** [comment]
Ah, that makes sense.
And thanks for the new screenshot. That can't be the issue.
It looks to me like some JS error somewhere. After selecting the file, the list with the avatars should close, and that is not happening.
Are you on the latest version? v2.21.1 ?
Could you please try to clear the cache and try again? (ctrl + shift + r to reload the page without cache or maybe try an incognito window)
Very strange that the browser is showing a JS error but showing HTML instead.

Thank you again.

**Comment by TheGuardianLight** [comment]
I'm on the latest version: v2.21.1.

And the same thing happens despite using incognito mode or clearing the cache.
Incidentally, I'd also like to take this opportunity to inform you that after logging in, when I click on one of the "subscription", "settings", "admin" or other items, I'm asked to log in again. (unless the "stay connected" button is ticked).

**Comment by ellite** [comment]
That is very strange. 
Do you have any browser extension that might mess with scripts or cookies?

**Comment by TheGuardianLight** [comment]
The only extensions I have in my browser are : 

- Shazam
- SwissTransfer by Infomaniak
- ublock origin (which is deactivated on my sites)
- Bitwarden
- Simple Login
- DeepL
- FetchV (to download certain videos)

cSo as far as I'm concerned, I don't have an activated extension that makes any changes to the site.

**Comment by ellite** [comment]
I'm really at a loss. I have no clue what your problems might be.
Can you try a different browser maybe? To see if all the issues remain.
I would understand if an issue on the avatar upload would pass a bit unnoticed, but the issue with the sessions I am quite sure would have been widely reported by now.

**Comment by TheGuardianLight** [comment]
I tried on Firefox (because I was on Microsoft Edge) and the same error occurred. However, in the console it gives me another location: 

![image](https://github.com/user-attachments/assets/7dd8450e-26c8-4894-90fe-92554d8490ed)

**Comment by TheGuardianLight** [comment]
I should also point out that I use Wallos with Docker

**Comment by ellite** [comment]
While examining the code, I found something in the service-worker that might cause the logout issue you mentioned.
Will keep looking for what might be causing the one with the avatar upload.

**Comment by TheGuardianLight** [comment]
Alright !

**Comment by ellite** [comment]
Hi. I've just released v2.21.2 , with the fix for the logout issue (not sure it is the same issue you had)
Also includes other fixed.
Please let me know if it fixed anything for you.

**Comment by ellite** [comment]
Yeap, in theory, with docker, it should behave the same for everyone.
I found some potential issues while looking at the avatar upload. But completely unrelated to your issue.
I don't understand why the JS error reported on the console is not giving the correct line. Without knowing it exactly, I don't think I can pinpoint the issue.
Would appreciate if you could try to see if other browser would return a more accurate error message and location.
Thanks.

**Comment by TheGuardianLight** [comment]
I tried it on Google Chrome (based on Chromium) :

![image](https://github.com/user-attachments/assets/643686e4-3cfc-4214-9ac4-964d93c15315)

On Microsoft Edge (based on Chromium) :

![image](https://github.com/user-attachments/assets/62af6bb6-992b-4100-b8ff-faa62a96c871)

On Firefox : 

![image](https://github.com/user-attachments/assets/b44049f7-cd9f-4608-8653-7ca9ce6f32e9)

**Comment by ellite** [comment]
That's crazy. And clicking on the settings.php:122 shows that same block of HTML still?

**Comment by ellite** [comment]
And when exactly does that error show?

**Comment by TheGuardianLight** [comment]
> That's crazy. And clicking on the settings.php:122 shows that same block of HTML still?

For Edge and Chrome :

![image](https://github.com/user-attachments/assets/cfc1e6d5-7a54-41ac-9387-979f5ad1ac7b)
![image](https://github.com/user-attachments/assets/12a7fecd-642c-41ea-a229-07d66568d7e2)

For Firefox : 

![image](https://github.com/user-attachments/assets/fff6509f-01c0-4fff-9ef6-ba79c0d65632)



> And when exactly does that error show?

This error appears after I've validated the file to be uploaded (.png file).

**Comment by ellite** [comment]
Thank you very much again for all the details.
I'll keep looking and keep you up to date if I find something.

**Comment by TheGuardianLight** [comment]
You're welcome !

**Comment by ellite** [comment]
Maybe I found the issue.
There's a JS function on the onchange of the button that sends the error message with it. And the French version of the error message has a ' in it. I really hope that this was the issue.
The release of 2.21.3 should hopefully fix it.

**Comment by TheGuardianLight** [comment]
Yup ! The release of 2.21.3 fix the issue !

**Comment by ellite** [comment]
Ah. Awesome. This was a hard one 😅
Thanks for the detailed report.

**Comment by TheGuardianLight** [comment]
We agree that this kind of stupid bug is often the most complicated to find xD
