### ISSUE TITLE
[FEATURE REQUEST] Allow to set a URL

### ISSUE THREAD

**Issue by TheZoker** [ellite/Wallos#48]
Would be nice, if in the subscription editor there was an URL field, that allows to set a url for the service

**Comment by devzwf** [comment]
Hello,
the url would be for which purpose ?
i mean , adding this info to the DB is ok , but where would it be displayed ? 
or would you see it being link to the icon of the subscription for an easy visit ?

**Comment by ellite** [comment]
Added: https://github.com/ellite/Wallos/commit/f4da6b735ef3db1b30caf23464e5a5596d308dfb
