### ISSUE TITLE
[BUG] Problem sorting by date when adding or modifying a subscription

### ISSUE THREAD

**Issue by TheGuardianLight** [ellite/Wallos#481]
I've noticed that when I add or modify a subscription, the subscriptions are no longer sorted by date, unless the window is refreshed.

Example of what I see after adding or modifying a subscription: 

![image](https://github.com/user-attachments/assets/b4e03c86-ce06-4e5e-90fc-d012c426edeb)

I'm not getting any errors in the console though.

**Comment by ellite** [comment]
Hi.
Is this still the case?
I release a fix for the sorting meanwhile. But since I could not reproduce this specific one, I am not sure if this was also solved.

Regards.

**Comment by TheGuardianLight** [comment]
Not resolved sadly.
I will make a video for you in the future day if I remember to do it to show you.

**Comment by ellite** [comment]
Thanks.

**Comment by TheGuardianLight** [comment]
https://github.com/user-attachments/assets/b2f4f3d8-cece-4158-835d-54b615775a82

There is a video of the issue
