### ISSUE TITLE
Billing Cycle

### ISSUE THREAD

**Issue by edalcin** [ellite/Wallos#49]
Hi! Wonderful app. I'm wondering what's the "Billing Cycle". I have a subscription that I have to pay every 3 years. There is an option for this? Maybe it is a "Feature Request".

**Comment by ellite** [comment]
You can use billing cycle 3 - Yearly
That means every 3 years. I need better wording there.
Regards.

**Comment by edalcin** [comment]
> You can use billing cycle 3 - Yearly That means every 3 years. I need better wording there. Regards.

Brilliant! Thanks!
