### ISSUE TITLE
[Feature Request]: allow multi select in filter

### ISSUE THREAD

**Issue by tbleiker** [ellite/Wallos#495]
It would be nice if multiple categories and/or payment methods can be selected as filter.

**Comment by teschiopol** [comment]
@ellite I create a pull request for payments in the dashboard view. If it's okay, I will replicate it for category also and in other views.

**Comment by ellite** [comment]
Hi. I've been wanting to do this for a long time. Didn't have the time for it. 
I will have a look into @teschiopol 's PR when I have some time, and maybe work from there. 
Thanks @tbleiker for the suggestion and @teschiopol for the contributions.

**Comment by ellite** [comment]
It's live on version 2.23.0
Thank you so much @teschiopol 👌
