### ISSUE TITLE
How updates works ?

### ISSUE THREAD

**Issue by Raxiel1987** [ellite/Wallos#50]
When an update is avaiable how to apply? Or is it automatic?

**Comment by ellite** [comment]
If you're using docker:

Pull the latest Docker image.
Stop and remove running containers.
Create and run containers with the updated image.

What I do instead is using Watchtower to keep all my containers automatically up to date.

https://containrrr.dev/watchtower/

**Comment by ellite** [comment]
I've updated the readme file with further instructions.
First, backup your wallos.db to somewhere safe, just in case.
If you used git clone to set it up, just do git pull and run the db migrator. `http://domain.example/endpoints/db/migrate.php`
If you've downloaded the repo, just download the current version and overwrite the files on your current installation. After that run the db migrator. `http://domain.example/endpoints/db/migrate.php`
