### ISSUE TITLE
[FEATURE REQUEST] Split docker release in latest and dev tag, use github release feature

### ISSUE THREAD

**Issue by TheZoker** [ellite/Wallos#51]
I would recommend, that the `latest` tag docker for the image is only update with a new release.

This means:
- Use github release function to create a new release and add a changelog (and maybe breaking chances). Similar to how immich or paperless ngx does it (e.g. https://github.com/immich-app/immich/releases/tag/v1.86.0)
- Only update the latest tag, when a new github release is created
- Create a new docker tag called `dev` (or similar) which is updated on every commit

This would allow people to use the docker default latest tag and only update on new releases and not on new commit. 

All of this is nice to have, but would be nice :) 

BTW love this little tool, very helpful ❤️

**Comment by noevidenz** [comment]
Instead of using the `latest` tag, it might be better to use a major version tag, such as `1.x` and `2.x`.

The trouble with `latest` is that someone could accidentally upgrade between major versions when a version 2.0 becomes the latest release. Using a major version number will allow people to safely pin to compatible versions and require them to deliberately change the image tag when they want to upgrade.

Besides that, having a stable release tag and a dev tag seems like a sensible approach.

**Comment by devzwf** [comment]
Agree with
keep updating the latest tag is shopping for a disaster.
i suggest to have 4 kind of tags :

- edge or dev : tag pointing to the cutting edge build - so if someone want to be always on the dge of the dev .. he do not hunter for version number
- latest : tag for the latest release stable - so if someone want to be alway on the stable.....
- version : what ever @ellite want , either major.minor.increment or year.day.increment  - for those who like to pin to a special version
- version-dev :  what ever @ellite want , either major.minor.increment-dev or year.day.increment-dev - for those who like to pin to a special version

just some food for the discussion

**Comment by RoguedBear** [comment]
This is the iteration I was thinking on maintaining tags while giving the author more control when to release stable/beta/nightly releases:
- 3 actions:
   1) `release-stable`: takes in the git tag as an input and tags it with `latest`/`stable`/`<version>`
   2) `release-dev`: same as above but for tagging dev builds `<version>-dev`
   3) the 3rd one will auto build on every new git tag and publish the image. (maybe under `<version>-rc` or `<version>-edge`?)

i still feel this setup could be fleshed out more. 
I would love take this up and contribute a PR if @ellite approves that

**Comment by devzwf** [comment]
@RoguedBear i like it 
let contribute a PR

**Comment by RoguedBear** [comment]
@devzwf can you assign this issue to me then?
I was looking at the workflow file, I think I should be able to add this functionality in the same workflow file only

**Comment by devzwf** [comment]
I would love to but only @ellite can for now.
