### ISSUE TITLE
PHP warnings about undefined variable

### ISSUE THREAD

**Issue by Adikso** [ellite/Wallos#511]
I just updated Wallos (docker) and the following warnings are shown on the top of the page:
```
Warning: Undefined variable $params in /var/www/html/index.php on line 108
Warning: foreach() argument must be of type array|object, null given in /var/www/html/index.php on line 108
```
![Screenshot_20240901_231120](https://github.com/user-attachments/assets/4f715cac-8e9b-44f4-9e04-6e965acc03c6)

Version: v2.23.0
Docker image: bellamy/wallos:latest

**Comment by Node815** [comment]
I can confirm after the latest update.  I have the same error.

**Comment by ellite** [comment]
Thanks. I initialized the variable on the wrong place.
A fix is being released.
