### ISSUE TITLE
Dose Category support customization?

### ISSUE THREAD

**Issue by GOUKI9999** [ellite/Wallos#523]
Hello, I would like to ask if the Category supports customization. Currently, I have several subscriptions, such as Amazon (shopping) and some ISP-like services—yes, I also consider them as subscriptions. I manage all my recurring payments through Wallos, and it’s challenging to determine the appropriate Category for them.

Additionally, there may be very specific categories or subcategories (like AI services), so I think offering customizable Categories could be a solution. Of course, it might be possible to configure this through a settings file, but I may not have found the relevant documentation. If that’s the case, I apologize for the disturbance.

**Comment by ellite** [comment]
Hi. It is available on the settings page.

![image](https://github.com/user-attachments/assets/8e60642a-4935-4cf8-a511-6cb7eea2c26f)

Regards

**Comment by GOUKI9999** [comment]
OMG I missed it ,thx for the replySent from Android device2024年9月26日 14:25，Miguel Ribeiro ***@***.***>写道：
Hi. It is available on the settings page.
4019BB12-35D7-4E2F-B00A-058B77F9289F.png (view on web)
Regards
