### ISSUE TITLE
[Bug] Currency and date format not following browser locale 

### ISSUE THREAD

**Issue by jpbaril** [ellite/Wallos#527]
Even though my browsers (I tried multiple) are set to prefer "French" as  webpage language, Wallos still formats dates and currencies as if set to "English" language.

This feature was added almost a year ago with https://github.com/ellite/Wallos/pull/53 but it does not seem to work here.

In below screenshot it should have appeared as per text added in red.
![Wallos-Subscription-Tracker](https://github.com/user-attachments/assets/9bf5b178-f847-4399-abf8-336af957ebe2)

N.B. This is the second time I open this issue. Initial issue completely disappeared from Github (i.e. it's not just "closed" it's nowhere to be found which is something I never experienced before.)

**Comment by ellite** [comment]
Hi. Yes, I remember. Didn't have a time to look at it yet.
Thanks for reopening.

**Comment by jpbaril** [comment]
For date format, it's very simple, current code just does NOT localize dates. It's hard-coded to English format.
https://github.com/ellite/Wallos/blob/40593fdc4a82775c0afc2226129220aed6ee6bae/index.php#L337
I'm still searching to find out if months' names are even supposed to be translated.

**Comment by jpbaril** [comment]
I tested something, I hard-coded the locale to 'fr_FR' in https://github.com/ellite/Wallos/blob/main/includes/currency_formatter.php

```
final class CurrencyFormatter
{
    private static $instance;

    private static function getInstance()
    {
        if (self::$instance === null) {                                       
            self::$instance = new NumberFormatter('fr_FR', NumberFormatter::CURRENCY);                                                                      
        }    
    echo self::$instance->getPattern();                                           
    return self::$instance;                                                         
    }                                                                             
                                                     
    public static function format($amount, $currency)
    {                                                                                
    return self::getInstance()->formatCurrency($amount,$currency);                   
    }                                                                                 
} 
```

Notice that I added the line "echo self::$instance->getPattern();" just for debugging.
The output was: "¤#,##0.00" which is not the "fr_FR" nor "fr_CA" format. It's probably php defaulting to "en_US". The french format should rather be "# ##0,00 ¤".
So, there is something wrong in the creation of the "NumberFormatter" object.

**Comment by jpbaril** [comment]
I edited the Dockerfile and added Alpine package "icu-data-full" then recreated the image.
It now correctly works for the currency technically speaking.
![Capture d’écran du 2024-09-28 22-11-09](https://github.com/user-attachments/assets/3949cfe3-2fc4-460c-9b44-dda0531f6383)

Now, I suppose it would just be a matter of adapting the app code so to not show "CA" after the dollar sign if canadian dollars are my main currency.

And as mentioned above for the dates format it's just that the current app code does not even try to format it to the user locale.

**Comment by ellite** [comment]
Hi. This is implemented on 2.26.0
Hope it works.
Regards.

**Comment by jpbaril** [comment]
> Hi. This is implemented on 2.26.0 Hope it works. Regards.
@ellite 
Unfortunately, no.
I don't see the Alpine package "icu-data-full" having been added to the Dockerfile.
Maybe you have a way to avoid adding that package, but on my side that was the trick to make it work.

**Comment by ellite** [comment]
No. I only saw the rest of your messages after implementing it. I used PHOs intl extension.

**Comment by ellite** [comment]
Oh. And I only worked on the dates. I'll look into the currencies later.

**Comment by jpbaril** [comment]
I think that the current code is fine for currency formating as long as the "icu-data-full" package is added.
I again recreated the docker image with latest code and with "icu-data-full" added and it looks almost perfect.
![Capture d’écran du 2024-09-29 18-45-49](https://github.com/user-attachments/assets/b1939bca-5f6e-4443-8ecc-7a52ad542210)

Again, I would just like to not have "CA" after the "$" sign as Canadian dollars is my main currency. For other countries dollars, like USA and Australia, it's perfect to have additional "US" or "AUS".

**Comment by ellite** [comment]
Thanks. I'll check.
