### ISSUE TITLE
[Bug] Custom Currency Conversion Not Working

### ISSUE THREAD

**Issue by YamenSharaf** [ellite/Wallos#539]
Hello,
So I added a custom currency (Egyptian Pound), which is supported in fixer.io
![Screenshot 2024-10-04 at 13 22 48@2x](https://github.com/user-attachments/assets/bb2e00ef-0fbf-4597-b10b-a5584052983d)
![Screenshot 2024-10-04 at 13 23 16@2x](https://github.com/user-attachments/assets/92225a38-ec6b-4df4-8be7-80bac807f189)

I can add a subscription using the UI in that currency
![Screenshot 2024-10-04 at 13 23 40@2x](https://github.com/user-attachments/assets/50af698f-5c63-40c8-98fb-1fa385b9b2f2)

but it shows in the UI with **the wrong currency**
![Screenshot 2024-10-04 at 13 25 02@2x](https://github.com/user-attachments/assets/e41b71f0-739e-4ca9-9336-d5d7eec7c933)

I have conversion enabled for Euros and also showing the original price, but it seems to work only for USD and GBP
![Screenshot 2024-10-04 at 13 27 09@2x](https://github.com/user-attachments/assets/5732bb22-36a0-4618-b6fc-7361a8188927)

**Comment by YamenSharaf** [comment]
Seems to have worked when I switched to APILayer.

**Comment by ellite** [comment]
Glad it's working.
