### ISSUE TITLE
[Possible Bug] Subscription logo will be replaced/updated after editing

### ISSUE THREAD

**Issue by ZetaExx** [ellite/Wallos#54]
Version 1.0
Plattform: Docker
OS: Unraid
Used Browser: Chrome Version 119.0.6045.124

Foremost, THANK YOU for this wonderful project and your efforts.

If I edit an existing subscription, **after** I added a new one, the logo will be replaced with the one from the subscription I added before.
I used the web search to and both logos. This also happens if I edit a logo in a subscription and edit another one, it always replaces the logo with the last set one.
Furthermore, I am able to reproduce this behavior every time. It is not happening after a page refresh.

**Comment by ellite** [comment]
Hi, thank you for the report. I will have a look.

**Comment by ellite** [comment]
Should be fixed: https://github.com/ellite/Wallos/commit/773bc7ca82f81da56bb2f6bc25d2f8b78c376084
