### ISSUE TITLE
[FEATURE REQUEST] Adding Type || Bucket || Area to subscriptions

### ISSUE THREAD

**Issue by ZetaExx** [ellite/Wallos#55]
A Possibility to assign a Type, Bucket, or Area (I'm lacking the proper name) besides the categories to cluster the types of expenses.
For example, so a user can create a bucket for:
- online subscriptions (Netflix, Prime, M365, Google One, etc..)
- basic subscriptions (Internet Provider, Mobile Phone, car insurance etc..) 
- budgetary subscriptions/contracts (rent, car leasing, power, etc..)
or other areas they like to.

The main reason, of course, would be to get better stats on the individual buckets. Because the amount per month greatly differs, so the stats combining all subscriptions is pretty useless. Filters for this would be needed -> #56 

And I know the direction of Wallos is for subs only, but one could argue rent and so on is just a bigger type of sub :)

**Comment by ellite** [comment]
This will not be implemented for now. 
This will be kept simple with only the categories.
Regards and thank you for the request.
