### ISSUE TITLE
[FEATURE REQUEST] Filter on Main and Stats page

### ISSUE THREAD

**Issue by ZetaExx** [ellite/Wallos#56]
A filter function beside the Sort function would be great.
To filter the fields within the subscriptions on the main page and the stats page. 
Furthermore, the option to save a filter to a view.

On the stats page, the filter could update the “General Statistics” depending on the filter or saved view.
It would be good if the "General Statistics" updates depending on which category is crossed out /deselected on the split view.

Maybe saved views or favorite saved views could be displayed as a button to quick filter.

**Comment by ellite** [comment]
A small part of this was just released.
You can now use filters on the settings page.
Regards.

**Comment by ellite** [comment]
Filters are now also available on the dashboard.
