### ISSUE TITLE
[Feature Request] Add Subscription Notes and URL to Webhook Payload

### ISSUE THREAD

**Issue by YamenSharaf** [ellite/Wallos#561]
## Request
Currently, it seems that the following variables are available to webhooks:
```
{{days_until}}, {{subscription_name}}, {{subscription_price}}, {{subscription_currency}}, {{subscription_category}}, {{subscription_date}}, {{subscription_payer}}, {{subscription_days_until_payment}}
```
It would be great to get the other subscription fields as well, namely the notes and URL.

## Use-case
My use-case for this is that while most of my subscriptions are paid automatically, some of them are credit-based and as such, even though they may be paid annually, manual interaction is needed. There is no field to signify that, so I use the notes to leave a note saying something "paid manually".

This is useless now, but I'm thinking if I can get this value along with the link in the webhook payload, I can pass that information to Home Assistant, and when the notes have the word `manual`, for instance, I can create a to-do item in Todoist with Home Assistant that tells me I should pay that particular subscription.

**Comment by ellite** [comment]
Will be available soon.

**Comment by YamenSharaf** [comment]
Thank you
