### ISSUE TITLE
The variables of Wallos are not recognized in the Synology Chat.

### ISSUE THREAD

**Issue by bzmshang** [ellite/Wallos#571]
![image](https://github.com/user-attachments/assets/69691c73-e2e2-4192-b653-637dd197bd87)
![image](https://github.com/user-attachments/assets/56685434-368f-477e-94f4-7abb870ca8ac)
![image](https://github.com/user-attachments/assets/2c43ad60-5b7c-4812-9073-555bafee23d7)
Is it an issue with my settings or is there a problem with the variables?

**Comment by ellite** [comment]
Hi, you need your variables inside a "{{subscriptions}}" array.

```
{
    "days_until": "{{days_until}}",
    "{{subscriptions}}": [
        {
            "name": "{{subscription_name}}",
            "price": "{{subscription_price}}",
            "currency": "{{subscription_currency}}",
            "category": "{{subscription_category}}",
            "date": "{{subscription_date}}",
            "payer": "{{subscription_payer}}",
            "days": "{{subscription_days_until_payment}}",
            "notes": "{{subscription_notes}}",
            "url": "{{subscription_url}}"
        }
    ]

}
```

**Comment by ellite** [comment]
I'll install da chat and try to find a working payload. I'll come back to you.

**Comment by ellite** [comment]
Just released Version 2.31.0. It will treat the payload as a string if it is not a valid JSON object.
Which is the case of the payload for DS Chat.
It won't handle the iterator {{subscriptions}} and will instead send multiple notifications if there's more than one subscription.
You can leave the field at the bottom empty and just use the same payload from your screen shots.
Please let me know if it works.

**Comment by ellite** [comment]
Yes, that looks correct.
You can empty the field after the payload.
The connection test does not replace the variables.
Only the actual notifications will.

**Comment by ellite** [comment]
No no. Don't remove payload.
I mean the second text field, it can be empty

**Comment by ellite** [comment]
2 👌

**Comment by ellite** [comment]
I forgot about the `{{days_until}}`. I'll release a fix in a few minutes.
But I would recommend using `{{subscription_days_until_payment}}` nevertheless.
