### ISSUE TITLE
Issue with setting up Email Notification

### ISSUE THREAD

**Issue by melroy-bsk** [ellite/Wallos#579]
Hi,

So I have recently started using Wallos v2.30.1, and have to say it's pretty good. 
I am trying to setup notifications specifically Email.

My setup is a cloud hosted instance, with Portainer sitting behind Traefik. I am using Mailgun and tested the SMTP credentials with a simple nodejs application. 

When I test the SMTP credentials with Wallos I get a 504 status code of Nginx. 

I tested with a open web hook and it works perfectly.

I still cannot figure out what the issue is any help is appreciated.

**Comment by melroy-bsk** [comment]
I figured out what the issue was.

**Comment by wreckedcarzz** [comment]
Could you elaborate on how you fixed this? I'm struggling to get email notifications working as well and it would be useful info for others.

**Comment by melroy-bsk** [comment]
> Could you elaborate on how you fixed this? I'm struggling to get email notifications working as well and it would be useful info for others.

So my cloud provider (Scaleway) had a toggle on the dashboard to open up smtp. once I did this then I was able to send and receive.
