### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function fetchArray()

### ISSUE THREAD

**Issue by Nautilus34** [ellite/Wallos#581]
Hello, 

thank you for this great tool. 
Everything was working perfectly until now. 

When I clicked on "Delete orphan logos," I encountered a fatal error. 

Warning: SQLite3::query(): Unable to prepare statement: 1, no such table: user in /var/www/html/includes/checkuser.php on line 3

Fatal error: Uncaught Error: Call to a member function fetchArray() on bool in /var/www/html/includes/checkuser.php:4 Stack trace: #0 /var/www/html/includes/header.php(3): require_once() #1 /var/www/html/admin.php(2): require_once('/var/www/html/i...') #2 {main} thrown in /var/www/html/includes/checkuser.php on line 4

Could you please assist me? 
I can no longer access the application. 

Thank you.

**Comment by ellite** [comment]
Very strange. That endpoint doesn't even write to the database. So, something happened before that.
Either the DB was deleted or got corrupted somehow. First time I see this happening.

Are you running wallos on Docker?

**Comment by Nautilus34** [comment]
Yes I'am using Docker.

When I clicked on delete "orphan logo":

<img width="336" alt="Capture d’écran 2024-10-18 à 16 22 13" src="https://github.com/user-attachments/assets/e2dee1a4-b9fe-43ab-94db-a31346fd51f6">

It deletes the user table in SQLite3. 
I tested it twice, fortunately, I have a backup.

**Comment by ellite** [comment]
😱
Glad you have a backup.
Looking at the code nothing jumps out at me immediately.
I'll test it after work and see what is happening.
Thank you for the report.

**Comment by ellite** [comment]
Do you have the logos and database mounted on the same folder by any chance?

**Comment by Nautilus34** [comment]
Yes, exactly. 
The logos and the database are mounted in the same folder and on the same volume.

**Comment by ellite** [comment]
Then that makes sense.
If the database file is just mixed with the logos, the script counts it as an unused logo and deletes it.

You should separate them

```
volumes:
      - './db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'
```

**Comment by Nautilus34** [comment]
Thank you so much! 

That works perfectly. 
Now, I don’t have any orphaned logos anymore.

`docker run -d \
  --name wallos \
  -v /var/lib/docker/volumes/wallos/_data/db:/var/www/html/db \
  -v /var/lib/docker/volumes/wallos/_data/logo:/var/www/html/images/uploads/logos \
  -e TZ=Europe/Paris \
  -p 80:80 \
  --restart unless-stopped \
  bellamy/wallos:latest`
