### ISSUE TITLE
Docker install gets unresponsive - PM.max_children setting reached

### ISSUE THREAD

**Issue by timothevs** [ellite/Wallos#59]
Running on Docker, when I try to test the email notification, the app becomes unresponsive and the docker logs show this error.

`WARNING: [pool www] server reached pm.max_children setting (5), consider raising it`

**Comment by ellite** [comment]
Hopefully this fixes it. https://github.com/ellite/Wallos/commit/e03ebf3e5334d404b99336c02779fbdf15544b2e

**Comment by timothevs** [comment]
Thanks, that does fix it. FYI, you may want to document that the port for the SMTP should be a TLS port. I added the SSL port, and when I tried to send a test mail, the system became non-responsive with the error above.
