### ISSUE TITLE
Add self sign certificate 

### ISSUE THREAD

**Issue by D3an1el** [ellite/Wallos#590]
Hi

I get an error when i use notifications to  send to gotify that uses a self signed  certificate . Is it possible to add an option to be able to add self signed CA certs?

**Comment by ellite** [comment]
Hi. I will have a look.

**Comment by ellite** [comment]
On version 2.32.0 you can go to the notification settings and enable "Ignore ssl errors"

**Comment by Chiller2019** [comment]
Need this also for OIDC ....

**Comment by t-grm** [comment]
Hi, I'm using a self-signed certificate to proxy both Wallos and my self-hosted OIDC IdP server.

It causes the following error after a successful OIDC authentication (Wallos Docker container log):

`NOTICE: PHP message: [Wallos OIDC] Token exchange failed for auth.xxxxxxxx.internal: SSL certificate OpenSSL verify result: unable to get local issuer certificate (20)`

Is there a solution similar to the one applied for notifications?
Best
