### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by ewoks** [ellite/Wallos#596]
Created new subscription and got this error.
Unfortunatelly the log doesn't say anything about it. 

It turns out that I download a logo from a website and uploaded it as subsription image.

![image](https://github.com/user-attachments/assets/1f6cbdb1-d99a-4890-9f55-13427784e1c4)

**Comment by ellite** [comment]
Can you please open the developer tools on the browser, go to the network tab. Try to add the subscription again and and click on the failed request. Then click on the response tab and the error message there should be more descriptive.

**Comment by ellite** [comment]
Alright. Thank you
