### ISSUE TITLE
Add more date options

### ISSUE THREAD

**Issue by KatyPurry** [ellite/Wallos#6]
Thank you for this great project! I have a request, I pay for some services every 2 years (Protonmail), is it possible to have more choices? Thank you

**Comment by ellite** [comment]
It is possible. Just like on the screenshot below. Wording is probably a bit confusing.

<img width="599" alt="Screenshot 2023-11-10 192706" src="https://github.com/ellite/Wallos/assets/3831180/d7245549-87dd-4ebb-bb72-f0c9321a736f">

**Comment by KatyPurry** [comment]
Oh okay, I tougth it was 2x per year ! thank you

**Comment by ellite** [comment]
No problem!
