### ISSUE TITLE
[FEATURE REQUEST] Payment Method Icon adding feature

### ISSUE THREAD

**Issue by polash** [ellite/Wallos#60]
No option to add custom payment method like I am in Bangladesh we have micro payment system bKash, Nagad, Upay, Rocket, if we can use it on the payment system icon manually adding option than it would be perfect. 

Also BDT is missing from the currency we have to add it manually. If possible please add the currency BDT ৳

**Comment by ellite** [comment]
Custom payment methods are now available.
Regards.
