### ISSUE TITLE
[Feature - Request] Add link to subscription service website

### ISSUE THREAD

**Issue by tismofied** [ellite/Wallos#600]
I don't know if this has been requested but a URL hook we can add to the services to point to the website of the subscription to check if payment was processed or to make manual payment?

**Comment by TheGuardianLight** [comment]
Hi there !

You can do it there : 

![Capture](https://github.com/user-attachments/assets/7b60fc81-fda0-4058-a2c5-2492406aa708)

Once that's done, you'll get an icon like this one where when you click on it, you'll be redirected to the link you provided. : 

![Capture2](https://github.com/user-attachments/assets/93b6d68a-ff3c-484e-be10-914547e3d7e8)

**Comment by tismofied** [comment]
🤦‍♂️ I have totally missed that. Thank you so much for this great project.
