### ISSUE TITLE
Outlook's mailbox doesn't work

### ISSUE THREAD

**Issue by bzmshang** [ellite/Wallos#615]
![image](https://github.com/user-attachments/assets/f201622f-466b-4ac0-ad27-5c22c0c03ff7)
![image](https://github.com/user-attachments/assets/aaf3d880-353f-4c52-8ba0-4a8edcfe3af1)

**Comment by ellite** [comment]
Hi. Have you tried adding your email to the "from email" field at the bottom?

**Comment by ellite** [comment]
It says that there's an authentication error.

From the web:

To set it up, you’ll need Outlook’s SMTP server details and your email credentials. Here’s how to configure it:

	1.	SMTP Server: smtp.office365.com
	2.	Port: 587
	3.	Encryption: STARTTLS (TLS/SSL)
	4.	Username: Your full Outlook email address (e.g., yourname@outlook.com)
	5.	Password: Your Outlook account password (consider using an app-specific password if two-factor authentication is enabled)

After entering these details in your app’s SMTP settings, you should be able to send notifications via your Outlook email.
