### ISSUE TITLE
[Issue / Bug] When selecting annual renewal billing cycles, it does not correctly show cost

### ISSUE THREAD

**Issue by xxIndirect** [ellite/Wallos#62]
![image](https://github.com/ellite/Wallos/assets/94948825/ec2461a1-8b85-4a67-a562-5402e010935c)
As demonstrated in the image, I am setting certain subscriptions as renewals annually but instead of showing 69 yearly, I see 5.73 in the price field on the actual page. Is this intentional? Doesn't seem like it if the math isn't mathing.  I also have Office 365 Family set as 99/year and same behavior.

Example of flawed math being shown:
![image](https://github.com/ellite/Wallos/assets/94948825/257d257c-ea77-4113-b5a7-3608a65af1b2)

**Comment by ellite** [comment]
Showing the monthly price instead of yearly price is a setting you can enable on the settings page
`Calculate and show monthly price for all subscriptions`
But it does indeed seem to be a rounding issue or something else in that calculation, since it should be $5.75 instead of $5.73. I will have a look.

**Comment by xxIndirect** [comment]
> Showing the monthly price instead of yearly price is a setting you can enable on the settings page `Calculate and show monthly price for all subscriptions` But it does indeed seem to be a rounding issue or something else in that calculation, since it should be $5.75 instead of $5.73. I will have a look.

Thank you for the quick reply. Fixed the setting but did notice the rounding error in monthly calculation. Initially caught it when I set up last night and glad I reported. You can close this issue out whenever. Just wanted to make sure you were aware.

**Comment by ellite** [comment]
Should be fixed: https://github.com/ellite/Wallos/commit/1aaf043d89411da354e5ee64fee569767cfb0525
