### ISSUE TITLE
status displayed on the wallos interface is not updated automatically

### ISSUE THREAD

**Issue by KyleKwan2024** [ellite/Wallos#620]
How to solve the problem that the subscription status displayed on the wallos interface is not updated automatically ?

![image](https://github.com/user-attachments/assets/77497d96-a550-4fb4-b35b-8fe37e84019c)

**Comment by TheGuardianLight** [comment]
Indeed, same things to me. Actually need to go to the admin page and manually launch the "Uodate Next Payments" cronjob.

**Comment by ellite** [comment]
Hi. Won't it update even after one day?

I've seen it happen, but it would update on the next cronjob. I could never figure the reason it would not update in the first place.
