### ISSUE TITLE
Issues will Dashboard showing converted amount and Email Notification

### ISSUE THREAD

**Issue by miovo** [ellite/Wallos#623]
Version: v2.36.2
Method: Docker Compose

Searched the current Issues and I don't seem to see these:

1. Subscriptions with yearly payments, the amount shown on the dashboard is calculated to show what the "monthly" cost would be. Is this the intended logic? 
![Screenshot 2024-11-14 154723](https://github.com/user-attachments/assets/dc9ce1bb-2179-42ee-9dff-666e50e019f6)
![Screenshot 2024-11-14 155412](https://github.com/user-attachments/assets/22ad2e23-1e85-408a-9612-be54519fcd16)

2. Email notifications: Example:
On 11/12/2024, I got an email saying I have an upcoming renewal tomorrow 
"Apple Music Family for 16.99$ (tomorrow)

On 11/13/2024, I got an email saying I have an upcoming renewal tomorrow 
"Apple Music Family for 16.99$ (tomorrow), 
Nabu Casa for 65$ (tomorrow)"

In the email on 11/13, the Apple Music Family subscriptions should have said "(today)" because it was due on the 13th.

![11-12-2024](https://github.com/user-attachments/assets/163ad9e5-4e3c-4e94-9b3d-12f394fb60bf)
![11-13-2024](https://github.com/user-attachments/assets/f931ce50-9726-4cef-8b55-1fcff3d110d3)
![Screenshot 2024-11-14 160158](https://github.com/user-attachments/assets/1ab18c6d-c6b9-46d6-bfde-322b06522a78)

**Comment by ellite** [comment]
Hi.
The first one yes, if you've enabled it in the settings.
![image](https://github.com/user-attachments/assets/3340aceb-323a-4cf5-bd1d-3b94b3eadec3)

The second one I have to check.

**Comment by miovo** [comment]
Must have checked that box and not realized it!

**Comment by ellite** [comment]
The second one is a bug.
You should not have received a second notification for Apple Music on the same day of the payment. That's why the "Today" case was missing, and if it's not more than 1 day, it says "tomorrow".
I'll release a fix soon.

**Comment by ellite** [comment]
The second issue should now be fixed with v2.37.1
