### ISSUE TITLE
Latest update broke stuff

### ISSUE THREAD

**Issue by NightHawkATL** [ellite/Wallos#633]
![image](https://github.com/user-attachments/assets/2e754a0f-94c9-4be4-a5ad-9346ef548563)

I can't click the 3 dots to edit an entry and the "recurring" icon is huge.

**Comment by ellite** [comment]
Seems like a cache issue. You can try to do ctrl + shift + r

**Comment by ellite** [comment]
That's strange. Can you tell me which browser you're using ?

**Comment by NightHawkATL** [comment]
I am using the latest version of Firefox on Linux Mint.

**Comment by kazzyUK** [comment]
Just updated as well. and getting the same layout issue.

Tried in multiple browsers (edge, Chrome, Vivaldi) and also on Android. (samsung internet and chrome)

**Comment by ellite** [comment]
I can reproduce it on the my demo instance. I found the issue and will release a fix asap.
Thank you for reporting

**Comment by ellite** [comment]
It's released. Sorry about missing the issue.

**Comment by NightHawkATL** [comment]
> It's released. Sorry about missing the issue.

No worries. Thanks for the quick fix!

**Comment by burgerga** [comment]
Another tiny thing related to the auto renew functionality:
<img width="262" alt="image" src="https://github.com/user-attachments/assets/d7365006-a7bd-4d99-beb4-e60644354403">
The auto renew is on top of the logo search (possibly needs a z-index=-1?)

**Comment by ellite** [comment]
It's fixed v2.38.2
Thank you for reporting.

**Comment by burgerga** [comment]
Works perfect, thanks!
