### ISSUE TITLE
Undefined array key "auto_renew"

### ISSUE THREAD

**Issue by Fabaderheld** [ellite/Wallos#641]
Hi

after migrating the installation and restoring the backup, the main page is full with this waring

```
Warning
: Undefined array key "auto_renew" in
/var/www/html/index.php
on line
359
```

the backup was from version v2.36.2

Everything other looks fine and seems to work. Any idea how to get rid of this?

thanks

Faba

**Comment by ellite** [comment]
Hi. Sorry for the delay. You need to run the database migration again if you're restoring a db with the old schema.
Restarting the container should do it.

**Comment by Fabaderheld** [comment]
Hi,  okay I tried a lot but never restarted the container ! It works now thanks

regards

Fabian
