### ISSUE TITLE
Calendar error

### ISSUE THREAD

**Issue by NightHawkATL** [ellite/Wallos#649]
![image](https://github.com/user-attachments/assets/be82709c-53ac-4a8e-afc7-1b69d710338e)

After updating to test the iCal export, this is what I see. 

Wallos 2.39.0

**Comment by ellite** [comment]
Thanks for the report. 
I'll see what's the issue with the image.

Regards.

**Comment by ellite** [comment]
It's fixed now. Thanks.

**Comment by NightHawkATL** [comment]
I can confirm. Thanks!

![image](https://github.com/user-attachments/assets/1ae948c8-9657-4a62-8b32-998f3f440b48)
