### ISSUE TITLE
[BUG] Index.php doesn't show main content

### ISSUE THREAD

**Issue by D0T1X** [ellite/Wallos#65]
## Is there an existing issue for this?
- [x] I have searched the existing issues and found none describing the same bug.

## General information:
- [x] Can you reproduce the problem on two or more devices?
- Operating system: Windows 11
- Webbrowser: Firefox & MS Edge
- Webbrowser version: 120.0 & 119.0.2151.72 (respectively)

- Operating system: Android
- Webbrowser: Firefox & MS Edge
- Webbrowser version: 119.1.1

- Webserver: Litespeed
- PHP: 8.2.12

## Description
Since a couple of commits ago, Wallos doesn't load the <main></main> part of the index.php anymore. I'm not yet sure about the root cause or which exact commit caused this. I've also noticed during troubleshooting that often php isn't being specified in the "<?php" part of the opening tag. but instead something like "<? =" is present. I might not know about this syntax. However, from my current assumption that this is incorrect. Some web servers like litespeed are very picky about syntax and tend to fail. I expect this to be the case.

However when I change this myself the whole screen goes blank, so some other issue persists. I haven't yet had the opportunity to verify the issue doesn't exist on other webserver software, but I assume it doesn't because otherwise it probably had be caught.

I'm currently at this time (T23:44) unsure about how to resolve this Bug. I'm registering this issue for future reference and in a hope for collaboration.

## Reproducing
- Use Litespeed webserver.
- Follow installation or upgrade instructions on the Git repo
- Create an account.
- reach the homepage and discover the issue.
- All other pages work fine.

### Before edits
Homepage:
![image](https://github.com/ellite/Wallos/assets/65193216/d9a692f3-c4d8-4e32-95ce-8aa8a36c68f9)
All other pages working fine:
![image](https://github.com/ellite/Wallos/assets/65193216/df2257c1-1c8d-4df6-b71f-7744cd155756)
### After php edits:
Index.php becomes a completely blank screen:
![image](https://github.com/ellite/Wallos/assets/65193216/f1b3d790-767e-47dc-8af8-57f3c0fbcced)

### Both situations:
Apache seems to generate internal server errors. Which most likely are related to the PHP failing, however PHP logs aren't being displayed.
![image](https://github.com/ellite/Wallos/assets/65193216/4b913d7c-56b7-4e2e-83d3-7c212c0c676c)

**Comment by ellite** [comment]
No idea where to start looking without error logs.
But `<?= $var ?>` is the same as `<?php echo $var ?>`. That should not be the issue.

Can you add the following to the top of your `index.php`?

```
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

**Comment by D0T1X** [comment]
Ah well would you look at that. Strange though, I had error reporting enabled,I guess I must have made a typo somewhere.

Also thanks about the info about the `<?= $var ?>` situation. I haven't heard of that before and couldn't find anything searching for it online.

The logs I thought I wasn't getting back, but apparently I do:
`
Warning: SQLite3::prepare(): Unable to prepare statement: 1, no such column: enabled in /var/www/vhosts/<redacted>/wallos.<redacted>/includes/getdbkeys.php on line 20

Fatal error: Uncaught Error: Call to a member function bindValue() on bool in /var/www/vhosts/<redacted>/<redacted>/includes/getdbkeys.php:21 Stack trace: #0 /var/www/vhosts/prevos.eu/wallos.prevos.eu/index.php(3): require_once() #1 {main} thrown in /var/www/vhosts/prevos.eu/wallos.prevos.eu/includes/getdbkeys.php on line 21
`

**Comment by ellite** [comment]
Can you open on your browser: yourdomain:port/endpoints/db/migrate.php ?

**Comment by D0T1X** [comment]
Alright, Should have listened to that voice in the back of my head when the page was blank, that I should've checked up on that.

```
Warning: SQLite3::query(): Unable to prepare statement: 1, near "(": syntax error in /var/www/vhosts/<redacted>/<redacted>/migrations/000002.php on line 6

Fatal error: Uncaught Error: Call to a member function fetchArray() on bool in /var/www/vhosts/<redacted>/<redacted>/migrations/000002.php:7 Stack trace: #0 /var/www/vhosts/<redacted>/<redacted>/endpoints/db/migrate.php(43): require_once() #1 {main} thrown in /var/www/vhosts/<redacted>/<redacted>/migrations/000002.php on line 7
```

**Comment by ellite** [comment]
Strange. Here it works both on baremetal and docker.

Can you try to change migrations/000002.php to

```
$columnQuery = $db->query("PRAGMA table_info(payment_methods)");
$columnRequired = false;

while ($column = $columnQuery->fetchArray(SQLITE3_ASSOC)) {
    if ($column['name'] === 'enabled') {
        $columnRequired = true;
        break;
    }
}

if (!$columnRequired) {
    // 'enabled' column does not exist, add it
    $db->exec('ALTER TABLE payment_methods ADD COLUMN enabled BOOLEAN DEFAULT 1');
    
    // Set default value for existing records
    $db->exec('UPDATE payment_methods SET enabled = 1');
}
```

And change migratios/000003.php to

```
$columnQuery = $db->query("PRAGMA table_info(notifications)");
$columnRequired = false;

while ($column = $columnQuery->fetchArray(SQLITE3_ASSOC)) {
    if ($column['name'] === 'from_email') {
        $columnRequired = true;
        break;
    }
}

if (!$columnRequired) {
    // 'from_email' column does not exist, add it
    $db->exec('ALTER TABLE notifications ADD COLUMN from_email VARCHAR(255);');
}
```

**Comment by D0T1X** [comment]
Yep, That does the trick:
`Migration ../../migrations/000002.php completed successfully. Migration ../../migrations/000003.php completed successfully.`

**Comment by ellite** [comment]
Awesome. Now I have to figure out why the old code would work in some cases and not other cases.

Is the index.php working now?

**Comment by D0T1X** [comment]
Yes, flawlessly.

Anything you want me to test, check or otherwise? Otherwise I'm fine with closing the Issue.
Thank you very much for your assistance!

**Comment by ellite** [comment]
Perfect! No need. Thanks. I'll check if the PHP versions 8.0.5 vs 8.2.12 might be the issue.
Any time.
Enjoy wallos.

**Comment by D0T1X** [comment]
Definitely!
If you do want me to check something in the future. Feel free to reach out.
I'd love to help whenever I can. Cheers!
