### ISSUE TITLE
Add “Quarterly” as frequency

### ISSUE THREAD

**Issue by aayushus** [ellite/Wallos#66]
Some “Subscriptions” like Homeowner's Associations are paid Quarterly - Can you please add Quarterly as a payment frequency so we can track them?

**Comment by ellite** [comment]
You can set every three months by choosing billing cycle 3 - Monthly.

**Comment by aayushus** [comment]
@ellite got it: I thought it was the pay date since it goes till 31st.

**Comment by aayushus** [comment]
@ellite perhaps have it similar to category? I could go in settings, define a new frequency say “bi-weekly” and the duration, then when I create a new subscription, I can just select the frequency.
