### ISSUE TITLE
Undefined array key "HTTP_ACCEPT_LANGUAGE"

### ISSUE THREAD

**Issue by ApricotFarm** [ellite/Wallos#67]
I'm getting the follow error message in the first listed subscription:

"Warning: Undefined array key "HTTP_ACCEPT_LANGUAGE" in /var/www/html/includes/currency_formatter.php on line 10"

It is always the FIRST item listed, regardless of the sort order. I'm getting this error ONLY in Opera, even after clearing cache, restarting browser and computer. Works as expected in Firefox and Safari.

Wallos v1.0

### 💻 Operating System and Arch

Raspberry Pi OS bullseye (fully updated)

### 🌐 Browser

Opera One(version: 105.0.4970.34) (arm64) [macOS]

### 🐋 Docker Version

Docker 24.0.7 (API: 1.43)

Screenshots below:

![wallos 1 2023-12-08 at 3 41 01 AM](https://github.com/ellite/Wallos/assets/25875880/c203d945-324a-4c66-9cfb-ad586c993c16)
![wallos 2 2023-12-08 at 3 41 48 AM](https://github.com/ellite/Wallos/assets/25875880/ef605d49-cda7-4043-882c-7b9cbde662de)
![wallos 3 2023-12-08 at 3 42 57 AM](https://github.com/ellite/Wallos/assets/25875880/f2b3d1b1-1f6a-47e0-aa9f-03a7c0ba84b4)

**Comment by ellite** [comment]
Seems that the browser is not sending the HTTP_ACCEPT_LANGUAGE header.
Should be fixed with https://github.com/ellite/Wallos/commit/2d7fb4bb6d3674f1917a629028dff2736adda204

**Comment by ApricotFarm** [comment]
Great...thanks for getting on this so quickly! Do you have any sense when we'll see a new Docker image with the fix incorporated?

**Comment by ellite** [comment]
Should be already available.

**Comment by ApricotFarm** [comment]
Works great for me now. Thanks so much for being so attentive! Issue closed and fixed as far as I'm concerned.
