### ISSUE TITLE
Unable to see subscription names on mobile

### ISSUE THREAD

**Issue by Reddax** [ellite/Wallos#69]
On mobile, the names of the subscriptions aren't visible without having to click on each one.
Mobile device: Samsung Fold 4.
![Wallos](https://github.com/ellite/Wallos/assets/1349626/ad6466cd-7402-4809-814b-7fa2e5ac9bbb)

**Comment by ellite** [comment]
It's by design, as they would not fit. Logo is visible because it resizes, but the name is moved down. 
Also the rows look quite broken at that resolution.
I'll see if I can find a way around that.

**Comment by ellite** [comment]
The broken layout is now fixed. To see the name you can click the subscription and it will expand and show a second line with the name. Using a logo on the subscriptions helps differentiate them on the first line.
Regards.
