### ISSUE TITLE
[FEATURE REQUEST] Make notes visible

### ISSUE THREAD

**Issue by rsobaid** [ellite/Wallos#70]
I have multiple accounts/domain names on one service and its hard to distinguish which one is for renewal without clicking the edit button. I noticed there is a Notes field that is not in use or appearing anywhere. I know I can use Subscription name but the logo is not available. Thank you! Love the project!

**Comment by ellite** [comment]
Hi. This is implemented now. You can click the subscription to expand and show a second and 3rd line, which includes the notes.
Regards
