### ISSUE TITLE
May I ask if the Chinese version will be supported in the future?

### ISSUE THREAD

**Issue by wshia** [ellite/Wallos#71]
May I ask if the Chinese version will be supported in the future?

**Comment by devzwf** [comment]
#5

**Comment by ellite** [comment]
This is finally merged. Was a long time in progress.
https://github.com/ellite/Wallos/commit/d7366dcfb0413b99279d867164da438779454a59

For now released as docker images on the edge and dev tags. Will be creating the stable and latest images soon if I don't find any big issue with it.

I don't know Chinese, so we have to hope that some contributor creates the language files for it.

**Comment by ellite** [comment]
Chinese language added thanks to @QuietBlade

**Comment by wshia** [comment]
> 添加中文感谢@QuietBlade

I haven't read it yet, did he add Chinese?

**Comment by ellite** [comment]
Yes. Simplified Chinese.

**Comment by taoqiko** [comment]
> 是的。简体中文。

Can I add it to the existing server? Or do I need to download it again?

**Comment by ellite** [comment]
You have to update.
Update instructions are on the README.
The stable and latest docker images have not yet been updated, only edge and dev.
I'm still testing that everything works, and then I'll add this changes also to the remaining tags.
