### ISSUE TITLE
[Question] Exploring JSON Output Possibilities for Data Retrieval from */stats.php and Other Potential */api Endpoints

### ISSUE THREAD

**Issue by A-Void-Me** [ellite/Wallos#72]
I might have overlooked a certain function, or it could be non-existent.

Is it feasible to obtain the data from */stats.php in JSON format using a GET request? Alternatively, are there any other */api endpoints that I might be overlooking?

**Comment by ellite** [comment]
Not for the statistics. 
At the moment you can look into /endpoints and all those should work with get requests and return json. But there's none statistics related.
Regards.

**Comment by A-Void-Me** [comment]
thank you, got some data i need from /endpoints/subscriptions/get.php , just needed to calculate a bit (y)
![Screenshot 2024-01-06 234334](https://github.com/ellite/Wallos/assets/124217270/330dcea8-a41d-47e5-8892-d39f63ab1d3e)
