### ISSUE TITLE
[Feature Request] Add privacy.com to list of payment methods

### ISSUE THREAD

**Issue by eroc1990** [ellite/Wallos#76]
I know I could just attribute privacy.com to "Credit card", but being able to see which of my subscriptions I use Privacy.com for at a glance would be nice.

**Comment by NightHawkATL** [comment]
I second this.

**Comment by ellite** [comment]
I'm working on custom payment methods. Should be released today or tomorrow. Still have to test everything.

**Comment by ellite** [comment]
Custom payments is now live.
Regards.
