### ISSUE TITLE
Help - No registration step with Docker install

### ISSUE THREAD

**Issue by jpbaril** [ellite/Wallos#77]
Hi,

I just launched a fresh Wallos Docker container but I'm not greeted with the registration page, I'm directly brought to the login page. But I don't have a login yet...

**Comment by jpbaril** [comment]
I found the bug. There is a default user created by default in the database:
1|bellamy|k.d.mitnick@gmail.com|$2y$10$JqdQGSp3WCe9q2.cg8vIQOfma0ki4g/4BN9ymw2rqDKHJeyhqZf2m|1|0

**Comment by ellite** [comment]
Hi, thank you for the report.
I'll have a look.
Meanwhile you can just delete wallos.db and restart the container. It should recreate the database.

**Comment by ellite** [comment]
I've pushed a new docker image. But you still need to delete wallos.db from your mounted folder.
