### ISSUE TITLE
[Feature Request] Automatic Next Payment date

### ISSUE THREAD

**Issue by jacklocke** [ellite/Wallos#79]
what about a button to calculate Next Payment date?

example:
Billing Cycle => 1/Yearly

[calculate] => Next Payment add 1 year

**Comment by faethon** [comment]
I just spun up a docker with Wallos after reading about it in the weekly digest on the Lemmy selfhosted community. I like Wallos, but I agree, indeed it would be nice to have a button after each subscription to mark payment done, and then calculate the new date (month / year) for the next payment.

For now I am failing to see how things will be recalculated or updated...
