### ISSUE TITLE
Unable to send test email on Unraid

### ISSUE THREAD

**Issue by TheMarf** [ellite/Wallos#82]
Hello! This seems like a pretty cool app to stay on top of subscriptions.  I'm currently using this on Unraid via https://hub.docker.com/r/bellamy/wallos

When I attempt to send a test email I'm getting an error. I've tried both ports 465 & 587.  I confirmed the credentials work as I currently use the exact same settings for unraid email notifications.  After reading other threads, I've also tried populating the from email address with the same account to eliminate.

![image](https://github.com/ellite/Wallos/assets/19783744/1be3f269-7638-439e-899b-14399a3078b1)
![image](https://github.com/ellite/Wallos/assets/19783744/64b5d185-e496-4d91-9f87-c05e2799c717)

**Comment by TheMarf** [comment]
Current Unraid SMTP settings for reference
![image](https://github.com/ellite/Wallos/assets/19783744/7691b96b-0c39-43b9-8dc9-a4899c67f3e5)

**Comment by ellite** [comment]
Hi. Sorry for the delay.
I was going to ask if you're using "app password" instead of your gmail password as it was the only way it worked for me, but you mentioned it works on other projects, so it might not be it.
I have it working on port 587, which you also mention that you tried.
So I'm really out of ideas. Sorry.
`From email` should be necessary for gmail.

**Comment by devzwf** [comment]
i am able to replicate as well with gmail
i will try dig a bit

**Comment by ellite** [comment]
Can you please open the developer tools on your browser, and go to the network tab
Then press the test button and click the sendtestmail.php on the network panel.
And copy the response and paste it here?

**Comment by TheMarf** [comment]
Response below.  Sorry for the delay, was traveling for work.

<br />
<b>Fatal error</b>:  Uncaught PHPMailer\PHPMailer\Exception: SMTP Error: Could not connect to SMTP host. in /var/www/html/libs/PHPMailer/PHPMailer.php:2244
Stack trace:
#0 /var/www/html/libs/PHPMailer/PHPMailer.php(2023): PHPMailer\PHPMailer\PHPMailer-&gt;smtpConnect(Array)
#1 /var/www/html/libs/PHPMailer/PHPMailer.php(1682): PHPMailer\PHPMailer\PHPMailer-&gt;smtpSend('Date: Fri, 26 J...', 'This is a test ...')
#2 /var/www/html/libs/PHPMailer/PHPMailer.php(1516): PHPMailer\PHPMailer\PHPMailer-&gt;postSend()
#3 /var/www/html/endpoints/notifications/sendtestmail.php(57): PHPMailer\PHPMailer\PHPMailer-&gt;send()
#4 {main}
  thrown in <b>/var/www/html/libs/PHPMailer/PHPMailer.php</b> on line <b>2244</b><br />

**Comment by TheMarf** [comment]
If I clear the from email field, save, and test I get the below.

<br />
<b>Fatal error</b>:  Uncaught PHPMailer\PHPMailer\Exception: Invalid address:  (From):  in /var/www/html/libs/PHPMailer/PHPMailer.php:1324
Stack trace:
#0 /var/www/html/endpoints/notifications/sendtestmail.php(51): PHPMailer\PHPMailer\PHPMailer-&gt;setFrom('', 'Wallos App')
#1 {main}
  thrown in <b>/var/www/html/libs/PHPMailer/PHPMailer.php</b> on line <b>1324</b><br />

**Comment by zakiur** [comment]
I believe I am also having a similar problem sending SMTP mail notification with Gmail. I am using an App password for gmail. My Wallos instance is running in WSL2 using Docker. This started occurring just after the last update. Before the update I used to get double notification emails. I do not know if that had something to do with this.

Here is my error log from the Network panel

```
Fatal error: Uncaught PHPMailer\PHPMailer\Exception: Invalid address: (From): in /var/www/html/libs/PHPMailer/PHPMailer.php:1324 Stack trace: #0 /var/www/html/endpoints/notifications/sendtestmail.php(51): PHPMailer\PHPMailer\PHPMailer->setFrom('', 'Wallos App') #1 {main} thrown in /var/www/html/libs/PHPMailer/PHPMailer.php on line 1324
``` 
Readout from portainer logs:
```
127.0.0.1 -  31/Jan/2024:12:10:24 +1100 "POST /endpoints/notifications/sendtestmail.php" 200
```
Screenshot of settings page:
![image](https://github.com/ellite/Wallos/assets/23335795/16eb2daf-091d-4ac5-bb14-954bd2c0feb3)

**Comment by TheMarf** [comment]
@ellite 

Had a couple minutes today so just for shiggles I tried generating and using an app pw and inputting that with port 587 and it seems to work.  I swore I did that prior to posting but maybe I goofed?

**Comment by ellite** [comment]
Awesome. Glad it's working.

**Comment by zakiur** [comment]
So after reading @TheMarf comment, I regenerated a new app password for gmail. It did not work for me. When I put my email into the From email (Optional) field it started to work again. Strange maybe its not optional for Gmail. Anyway thanks for the help.
