### ISSUE TITLE
[Bug] Curency conversion not working

### ISSUE THREAD

**Issue by avataru** [ellite/Wallos#83]
Checking "Always convert and show prices on my main currency (slower)." doesn't seem to do what it's supposed to. I have a fixer API key set but the conversion option only seems to change the currency symbol while the value remains the same.

Additionally the stats page just adds the values, regardless of the currency, which makes it useless for multi-currency setups.

I think a quick fix for the stats page would be to split the stats by currency. As for the conversion you could allow users to use manual fixed rates if they don't want to use fixer or as a fallback.

**Comment by ellite** [comment]
On the settings page -> currencies section do you have a date on "Exchange rates last updated on" ?
If not, the cron job has not run yet, so you don't have exchange data. 
You can force it by changing the main currency on Settings -> User details and then changing it back to your preferred one.
Regards.

**Comment by avataru** [comment]
Just came to update the ticket with that info. I used the [API](http://192.168.1.99:8282/endpoints/currency/update_exchange.php) to manually update the rates and it's working. Maybe a button to manually trigger an update would be useful or just update it when the conversion option gets enabled.

**Comment by ellite** [comment]
Yes, that works as well. 
Probably when saving the API key would be a good time to do it. 
I'll look into it.
