### ISSUE TITLE
Unable to show the logo correctly on QnapNAS

### ISSUE THREAD

**Issue by EpsIotaPi** [ellite/Wallos#84]
Thank you for your amazing work!
When I run this project in QnapNAS (install by docker compose)
This problem did not appear when I run it on Mac (also install by docker compose)

![Sketches](https://github.com/ellite/Wallos/assets/29699430/053e95c5-20c2-446c-91c6-edd08acb0f53)

**Comment by ellite** [comment]
Hi. I've never seen that behavior.
Have you mounted the images folder?

**Comment by EpsIotaPi** [comment]
Yes, I'm sure I have mounted the image folder.
I use the same docker-compose.yml file in different machine(Mac and QnapNAS). The behaviour on Mac is normal, only the behaviour on QnapNAS is incorrect. Which is truely strange 😂.

I try to visit the logo image resource directly, it shows 403 Error.
the nginx log shows the following error:

```
2024/01/24 02:07:54 [error] 13#13: *31 open() "/var/www/html/images/uploads/logos/1706031370-Infuse-Pro.png" failed (13: Permission denied), client: 192.168.0.101, server: localhost, request: "GET /images/uploads/logos/1706031370-Infuse-Pro.png HTTP/1.1", host: "192.168.0.110:8282", referrer: "http://192.168.0.110:8282/"
2024/01/24 02:07:54 [error] 13#13: *40 open() "/var/www/html/images/uploads/logos/1706030878-PlayStation-Plus.png" failed (13: Permission denied), client: 192.168.0.101, server: localhost, request: "GET /images/uploads/logos/1706030878-PlayStation-Plus.png HTTP/1.1", host: "192.168.0.110:8282", referrer: "http://192.168.0.110:8282/"
2024/01/24 02:07:54 [error] 13#13: *41 open() "/var/www/html/images/uploads/logos/1706031660-iCloud.png" failed (13: Permission denied), client: 192.168.0.101, server: localhost, request: "GET /images/uploads/logos/1706031660-iCloud.png HTTP/1.1", host: "192.168.0.110:8282", referrer: "http://192.168.0.110:8282/"
```

ps: the logo is upload/search through the normal way, and I also trying to give the folder 777 permission, it did not fix the problem.

**Comment by devzwf** [comment]
403 error mean the access is Forbidden
verify the whole path to the logos

**Comment by EpsIotaPi** [comment]
I think the whole path is correct. For example:

<img width="834" alt="截屏2024-01-25 上午12 01 14" src="https://github.com/ellite/Wallos/assets/29699430/a08724db-6bba-45ad-923c-47a514018347">

<img width="1261" alt="截屏2024-01-25 上午12 02 33" src="https://github.com/ellite/Wallos/assets/29699430/893b9db5-bbea-4157-bd3e-a3e587211d2b">

**Comment by devzwf** [comment]
I mean permission

**Comment by devzwf** [comment]
please check permission of the whole path 
not only the file, the http server need to be able to traverse the path

**Comment by ellite** [comment]
Can you try:

`docker exec -it wallos /bin/sh`

and inside the container shell:

`cd /var/www/html/images/uploads/logos`
and
`ls -lah` 

Check who owns the files, it should be `www-data`

Then you can try:

```
chmod a+r /var/www/html/images/uploads/logos/*
chown -R www-data:www-data /var/www/html/images/uploads/logos
```

**Comment by EpsIotaPi** [comment]
I already give the full permission to `/var/www/html/images`, and I also try your command. Unfortunately, it did not fix the problem.

<img width="1239" alt="截屏2024-01-25 上午9 31 23" src="https://github.com/ellite/Wallos/assets/29699430/8e1c2d2c-b8af-4e61-8b61-b2e14ce05d8f">

**Comment by ellite** [comment]
I am at a loss. Sorry.
Maybe you can try to completely remove the container and mounted folders, and try a fresh install?
I really am out of ideas.

**Comment by EpsIotaPi** [comment]
Thank you so much for your consideration. I already try to remove the container before, it did not help.
I'll keep try to fix this, and if I figure out the reason, I'll reply to you through this issue.

**Comment by devzwf** [comment]
You need to not only remove container.,
you also need to remove the mounted folder for a fresh install.
i dont have Qnap , and cant reproduse on other systems i have :(

**Comment by mlclns** [comment]
I'm having the same issue in a docker container. The files, as far as I can tell, have the correct permissions
<img width="772" alt="Screenshot 2024-03-29 at 12 21 19" src="https://github.com/ellite/Wallos/assets/145590728/f67a895b-bece-4952-a1af-10f536d65c66">

However, I still get a 403 forbidden on the page
<img width="1033" alt="Screenshot 2024-03-29 at 12 23 52" src="https://github.com/ellite/Wallos/assets/145590728/851046ba-8aa6-40f8-b2b4-d47c02bf932a">

My docker compose is as follows (UID and GID env variables were added after to attempt to fix this issue to no avail):
```
version: '3.0'

services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - "9061:80/tcp"
    environment:
      TZ: 'America/New_York'
      UID: "1000"
      GID: "1000"
    # Volumes store your data between container upgrades
    volumes:
      - './db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped
```

**Comment by mlclns** [comment]
I have found a solution to this issue, which is allow docker to create a volume with the correct permissions by defining a volume in the docker compose, test it, then ```docker compose down``` and ```cp -a``` the volume data on the host to the folder you'll mount and mount it as a folder again in the compose before  doing ```docker compose up -d```.
