### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by EccTM** [ellite/Wallos#9]
Would it be possible to get an image built for arm systems?

**Comment by ellite** [comment]
I'm researching it at this very moment. It's my number one priority

**Comment by devzwf** [comment]
you should be able to just use buildx and add the platform 
i test it and seems to work

you can also use actions .... very powerful

**Comment by noevidenz** [comment]
This issue is addressed by PR #40

**Comment by ellite** [comment]
Thank you so much @noevidenz for the contribution!
