### ISSUE TITLE
Subscription form not entirely visible on smaller screen

### ISSUE THREAD

**Issue by CrowMash** [ellite/Wallos#91]
On small screens, the subscription form height is bigger than my browser height and I'm not able to user a scrollbar:

![image](https://github.com/ellite/Wallos/assets/9526631/d38aadd6-c2f8-45c7-ba46-26c39eb0f2a4)

If I put something like that in css, it fits better and allows me to use the scrollbar:
```css
max-height: calc(100vh - 44px);
overflow: auto;
```
(44px = padding top + padding bottom of .subscription-form)

![image](https://github.com/ellite/Wallos/assets/9526631/07480233-9090-4e6c-863f-07106f65bd01)

**Comment by devzwf** [comment]
Is it affecting normal screen rendering as well ?

**Comment by CrowMash** [comment]
Subscription form has a fixed height, so right now you MUST have that minimal height in order to see all fields.
When I test it, it looks like I need something like 800px on Google Chrome.

> Is it affecting normal screen rendering as well ?

If you are referring to my small fix, it does nothing if you have enough space.

**Comment by devzwf** [comment]
would you like craft a PR ? or i can do it 
let me know

**Comment by CrowMash** [comment]
> would you like craft a PR ? or i can do it tested it , seems all good let me know

You can do it if you want, I won't be able to do it before monday

**Comment by ellite** [comment]
I'll do it. I will not add the 44px spacing to the mobile version. I want to try some things.

**Comment by ellite** [comment]
https://github.com/ellite/Wallos/commit/ad9afb79fcc084385c4ca4b9d693b09bae59829d Should fix it.

**Comment by CrowMash** [comment]
Perfect!
