### ISSUE TITLE
[FEATURE REQUEST] Store display settings per user instead of per browser

### ISSUE THREAD

**Issue by My-Random-Thoughts** [ellite/Wallos#93]
The display settings are not stored per user, but per browser:

![image](https://github.com/ellite/Wallos/assets/21334396/03628840-6dc4-42a7-8749-00ca13544919)

The light/dark theme is particularly important, but the two tick boxes need to stored too.
 
 All other settings seem to be stored and shared between browsers, just not these ones.

**Comment by ellite** [comment]
Thought about exactly that earlier today. It's in the list to be implemented.
Thank you.

**Comment by ellite** [comment]
It's implemented. Regards.
