### ISSUE TITLE
[FEATURE REQUEST] Provide versioned container images

### ISSUE THREAD

**Issue by snyssen** [ellite/Wallos#94]
I would like to have versioned images so I can have predictable infrastructure deployments, greater control on how and when updates take place, and have an easier way to rollback changes if necessary. This is of course doable without a version tag by [pinning the image digest](https://github.com/snyssen/infra-snyssen.be/commit/d779541c6f8a6db3f304821895e7b09b4c3b9ebd), but it is harder to track changes and move between versions that way.

I would be willing to open a PR for this feature if that seems okay to you.  I use a standard methodology, [described in my blog ](https://snyssen.be/blog/automated-releases-versioning-and-publishing/), for handling versioning automatically, but it requires devs to adopt [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). If this is (understandably) an issue for you, I could instead provide a github action that would create versions based on manually attached git tags. Please let me know if this is a PR you would be interested in, and which system you would prefer.

**Comment by ellite** [comment]
I think this PR added something like this, no?
https://github.com/ellite/Wallos/pull/61

I would appreciate your input and contribution, because indeed having versioned releases would be much better.
I'll have a look at your blog as well.

**Comment by snyssen** [comment]
Yes, PR #61 is on the right track! Sorry I missed it earlier. The way it is implemented just requires more manual intervention since you have to first create a git tag by hand, and then run the workflow on the tag (and selecting the type of build). But if you are okay with those kind of manual steps it is great :slightly_smiling_face: 

You should note, however, that your current workflow won't create a github release. If you want to create one, you should add a step using `actions/create-release@v1` in the `build-image.yml` workflow, where you could reuse the tag; the creation of a github release is however purely cosmetic since the actual images are pushed to the Docker registry.

**Comment by ellite** [comment]
Feel free to open a PR. 🙌

**Comment by devzwf** [comment]
while we are at it , you should also start maintain a changelog

**Comment by snyssen** [comment]
I'll work on this when I get some time :) Not sure what you would prefer though: should I build on top of the existing workflow and only add github releases creation, or should I redo the workflow as described in my blog (thus requiring you to adopt conventional commits)?

**Comment by ellite** [comment]
Sorry, I didn't have time to read it yet. I'll try to do it today after work.

**Comment by ellite** [comment]
It sounds great.
Now... me remembering to do the conventional commits... might be hard 😱

**Comment by snyssen** [comment]
Seems like the pipeline is working as intended :smiley: I'm closing this issue then (forgot to add the closing keyword to my PR)
