### ISSUE TITLE
[Feature Request] Support for Pushover/other local notifications

### ISSUE THREAD

**Issue by n00b12345** [ellite/Wallos#97]
Support for [Pushover](https://pushover.net/) notifications or any other local notification, say [Gotify](https://gotify.net/), would be really nice.

Please consider it.

Thank you for making Wallos.

**Comment by ellite** [comment]
Hi. Thank you for your recommendation. This was already requested a few times. I haven't yet found the time to look into it.

**Comment by jpbaril** [comment]
Easiest way to implement this is to delegate the actual notification sending feature to other tools like: https://github.com/caronc/apprise or https://github.com/containrrr/shoutrrr
Both can be baked into your tool or be ran standalone by users and so be called upon by api.
I have both running standalone and have some other tools that have baked these into them.

**Comment by ellite** [comment]
Pushover, Gotify and others have been implemented. Enjoy.
